# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    silent: true
    cmds:
      - task: prereqs
      - task: check-spelling
      - task: run-validations

  # cspell: words prereqs
  prereqs:
    silent: true
    cmds:
    - |
      source ./build.sh
      check_prerequisites
  
  check-spelling:
    silent: true
    cmds:
    - |
      source ./build.sh
      check_spelling

  run-validations:
    silent: true
    cmds:
    - |
      source ./build.sh
      check_validations

  check-arm:
    silent: true
    cmds:
    - |
      source ./build.sh
      validate_arm_files

  check-json:
    silent: true
    cmds:
    - |
      source ./build.sh
      validate_json_files
  
  check-build:
    silent: true
    cmds:
    - |
      source ./build.sh
      validate_build

  build:
    silent: true
    cmds:
    - |
      source ./build.sh
      build_solution
  
  # Usage
  # deploy:my-rg-name:my-ws-name"Central US":3.3.0
  deploy:*:*:*:*:
    vars:      
      RESOURCE_GROUP: "{{index .MATCH 0}}"
      WORKSPACE: "{{index .MATCH 1}}"
      REGION: "{{index .MATCH 2}}"
      DEPLOY_VERSION: "{{index .MATCH 3}}"
    silent: true
    cmds:
    - |
      source ./build.sh
      deploy_to_azure "{{.RESOURCE_GROUP}}" "{{.WORKSPACE}}" "{{.REGION}}" "{{.DEPLOY_VERSION}}"
  
  # Usage
  # build-deploy:my-rg-name:my-ws-name:"Central US"
  build-deploy:*:*:*:
    vars:      
      RESOURCE_GROUP: "{{index .MATCH 0}}"
      WORKSPACE: "{{index .MATCH 1}}"
      REGION: "{{index .MATCH 2}}"
      DEPLOY_VERSION:
      # cspell: disable-next-line
        sh: pwsh -NoProfile -File ./get-new-version.ps1 Solutions/Tanium/Data
    silent: true
    cmds:
    - task: prereqs
    - task: check-spelling
    - task: run-validations
    - task: deploy:{{.RESOURCE_GROUP}}:{{.WORKSPACE}}:{{.REGION}}:{{.DEPLOY_VERSION}}
    