id: f8386a89-20c2-41ab-8ae2-bab88de65f81
name: MDE_FindDefenderSettingsOnEndpoints
description: |
  Find Endpoints policies settings via compliance settings in the registry
requiredDataConnectors:
- connectorId: MicrosoftThreatProtection
  dataTypes:
  - DeviceBaselineComplianceAssessment
query: |
  //Find Windows Defender Settings
  DeviceBaselineComplianceAssessment 
  | where Source contains "hkey_local_machine\\software\\policies\\microsoft\\windows defender\\"
  | project DeviceName, Source, CurrentValue

  //Find Windows Defender Security Center Settings
  DeviceBaselineComplianceAssessment 
  | where Source contains "HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Windows Defender Security Center\\"
  | project DeviceName, Source, CurrentValue
version: 1.0.1
metadata:
    source:
        kind: Community
    author:
        name: Matt Novitsch
    support:
        tier: Community
    categories:
        domains: [ "Security" ]