* [32mmaster[m
  [31mremotes/origin/1506-logicapp-fix[m
  [31mremotes/origin/250521-Yanivsh-Parser-Update[m
  [31mremotes/origin/AAD-Addition[m
  [31mremotes/origin/AADSync[m
  [31mremotes/origin/AADUserData[m
  [31mremotes/origin/AD4IoT-Playbooks[m
  [31mremotes/origin/AWS-CloudTrail-AzFunc[m
  [31mremotes/origin/Add-version-to-templates[m
  [31mremotes/origin/Amitbergman-patch-1[m
  [31mremotes/origin/Amitbergman-patch-10[m
  [31mremotes/origin/Amitbergman-patch-12[m
  [31mremotes/origin/Amitbergman-patch-13[m
  [31mremotes/origin/Amitbergman-patch-14[m
  [31mremotes/origin/Amitbergman-patch-15[m
  [31mremotes/origin/Amitbergman-patch-2[m
  [31mremotes/origin/Amitbergman-patch-21[m
  [31mremotes/origin/Amitbergman-patch-22[m
  [31mremotes/origin/Amitbergman-patch-23[m
  [31mremotes/origin/Amitbergman-patch-24[m
  [31mremotes/origin/Amitbergman-patch-25[m
  [31mremotes/origin/Amitbergman-patch-26[m
  [31mremotes/origin/Amitbergman-patch-27[m
  [31mremotes/origin/Amitbergman-patch-3[m
  [31mremotes/origin/Amitbergman-patch-32[m
  [31mremotes/origin/Amitbergman-patch-33[m
  [31mremotes/origin/Amitbergman-patch-35[m
  [31mremotes/origin/Amitbergman-patch-38[m
  [31mremotes/origin/Amitbergman-patch-4[m
  [31mremotes/origin/Amitbergman-patch-40[m
  [31mremotes/origin/Amitbergman-patch-41[m
  [31mremotes/origin/Amitbergman-patch-42[m
  [31mremotes/origin/Amitbergman-patch-5[m
  [31mremotes/origin/Amitbergman-patch-6[m
  [31mremotes/origin/Amitbergman-patch-7[m
  [31mremotes/origin/Amitbergman-patch-8[m
  [31mremotes/origin/Amitbergman-patch-9[m
  [31mremotes/origin/ArmorBoxTestBranch[m
  [31mremotes/origin/AzureKeyVaultWorkbook[m
  [31mremotes/origin/AzureKeyVault_Improvement[m
  [31mremotes/origin/BM-LogicApp-Fix[m
  [31mremotes/origin/BranchForTesting[m
  [31mremotes/origin/CMMCPolicyMapUpdate[m
  [31mremotes/origin/CMMCPolicyMapping[m
  [31mremotes/origin/Casesensitivityfix[m
  [31mremotes/origin/ChiaCryptoMining[m
  [31mremotes/origin/ChiaPlotting_Detection[m
  [31mremotes/origin/CiscoFirepower[m
  [31mremotes/origin/CliveW-MSFT-patch-11[m
  [31mremotes/origin/CliveW-MSFT-patch-12[m
  [31mremotes/origin/CliveW-MSFT-patch-13[m
  [31mremotes/origin/CliveW-MSFT-patch-14[m
  [31mremotes/origin/CliveW-MSFT-patch-8[m
  [31mremotes/origin/CoreAzureBackupAddition[m
  [31mremotes/origin/CustomTables_Feed[m
  [31mremotes/origin/D4ITOT[m
  [31mremotes/origin/DEV-0322-Serv-U[m
  [31mremotes/origin/DarkTraceRevertWorkbookFileRename[m
  [31mremotes/origin/DummyBranchToTestValidations[m
  [31mremotes/origin/DummyLogoValidationBranch[m
  [31mremotes/origin/FixingSampleData[m
  [31mremotes/origin/FoggyWeb[m
  [31mremotes/origin/Forcepoint-cloud-security-gateway[m
  [31mremotes/origin/Fortigate-linked-template[m
  [31mremotes/origin/GHFunc[m
  [31mremotes/origin/Get-TenableVlun[m
  [31mremotes/origin/HEAD[m -> origin/master
  [31mremotes/origin/IPCAzurePortalHuntingQuery[m
  [31mremotes/origin/Jira-move-toPlaybooks[m
  [31mremotes/origin/Jira-sync[m
  [31mremotes/origin/Lab-hunting-new-secation-1409[m
  [31mremotes/origin/Lab03-updates[m
  [31mremotes/origin/MITRE-ATT&CK-Solution_Update2[m
  [31mremotes/origin/MSHTML_Vuln_DetectionQuery[m
  [31mremotes/origin/Manganese_VPN-IOCs_with_has_any_ipv4[m
  [31mremotes/origin/MoveCiscoUmbrella_solution[m
  [31mremotes/origin/MovetoSolutionFolder[m
  [31mremotes/origin/NamedLocation-AdaptToGallery[m
  [31mremotes/origin/NamedPipeQueryparsingchanges[m
  [31mremotes/origin/NewLogicAppsConnectorExample[m
  [31mremotes/origin/NewTestBranch[m
  [31mremotes/origin/OMIGOD_FileMOve[m
  [31mremotes/origin/OMIGOD_GUIDChange[m
  [31mremotes/origin/OMI_Vuln_Query[m
  [31mremotes/origin/OMI_Vuln_Tag_Update[m
  [31mremotes/origin/PANOSadaptionToGallery[m
  [31mremotes/origin/PIMdisablingalertaddition[m
  [31mremotes/origin/PlaybooksGalleryAdaptions3[m
  [31mremotes/origin/PlaybooksGalleryAdaptions4[m
  [31mremotes/origin/PlaybooksGalleryAlignment[m
  [31mremotes/origin/PlaybooksGalleryAlignment1[m
  [31mremotes/origin/PostDeploymentInstructions[m
  [31mremotes/origin/QueryFixes[m
  [31mremotes/origin/QueryFixes1[m
  [31mremotes/origin/ReconactivitywithInteractivelogon[m
  [31mremotes/origin/RemoveDeprecatedTechnique[m
  [31mremotes/origin/ResetAAD-logicAPP[m
  [31mremotes/origin/SOAR-connectors-Private-Preview[m
  [31mremotes/origin/Sample_File_Delete[m
  [31mremotes/origin/SecurityRegulatoryCompliance[m
  [31mremotes/origin/SolutionNamesUpdate[m
  [31mremotes/origin/SophosXGFirewallSolutions[m
  [31mremotes/origin/Sourgum[m
  [31mremotes/origin/TestArmbox[m
  [31mremotes/origin/TestBranchToVerifyValidationFailure[m
  [31mremotes/origin/TestFix[m
  [31mremotes/origin/TestValidationsBranch[m
  [31mremotes/origin/TestingBranch[m
  [31mremotes/origin/ThreatIntelligenceWorkbookv2[m
  [31mremotes/origin/UpdateHolmTest[m
  [31mremotes/origin/Updating_Tampering_Query[m
  [31mremotes/origin/ZTWorkbookUpdate[m
  [31mremotes/origin/ZeroTrust-Workbook-&-Analytics[m
  [31mremotes/origin/ZeroTrustMappingUpdate[m
  [31mremotes/origin/ZeroTrustTIC3Mapping[m
  [31mremotes/origin/ZscalerPlaybooks[m
  [31mremotes/origin/adaptSendIngestionCostToGallery[m
  [31mremotes/origin/addAwsReadmeFile[m
  [31mremotes/origin/addAwsScript[m
  [31mremotes/origin/addvalidation[m
  [31mremotes/origin/alert-incident-trigger[m
  [31mremotes/origin/aprakash13-chiaCryptoIoC[m
  [31mremotes/origin/aprakash13-patch-1[m
  [31mremotes/origin/aprakash13-patch-2[m
  [31mremotes/origin/aprakash13-patch-3[m
  [31mremotes/origin/ashwin/connector-fixes[m
  [31mremotes/origin/bettertogether[m
  [31mremotes/origin/branchTest[m
  [31mremotes/origin/chboeh-patch-1[m
  [31mremotes/origin/clivew-msft-sept2021wu[m
  [31mremotes/origin/credentials_query[m
  [31mremotes/origin/dev/CustomExpansionQueries[m
  [31mremotes/origin/dev/DNS[m
  [31mremotes/origin/dev/Norm[m
  [31mremotes/origin/dev/Normali[m
  [31mremotes/origin/dev/Normalization[m
  [31mremotes/origin/dev/insights_preview/optimizedAccount[m
  [31mremotes/origin/dev/normalization/DEV-0322_SolarWinds_Serv-U_IOC[m
  [31mremotes/origin/dev/normalization/Email-flow[m
  [31mremotes/origin/dev/normalization/FileEvent010[m
  [31mremotes/origin/dev/normalization/FullASIMDeployment[m
  [31mremotes/origin/dev/normalization/IoTdeploy[m
  [31mremotes/origin/dev/normalization/WindowsEvents[m
  [31mremotes/origin/dev/normalization/add-network-to-sysmon-linux-deploy[m
  [31mremotes/origin/dev/normalization/authentication/UserParam[m
  [31mremotes/origin/dev/normalization/dns/011[m
  [31mremotes/origin/dev/normalization/dns/paramParsers[m
  [31mremotes/origin/dev/normalization/dns_entity[m
  [31mremotes/origin/dev/normalization/network-v2-full-deploy[m
  [31mremotes/origin/dev/normalization/networkYuval[m
  [31mremotes/origin/dev/normalization/network_v2[m
  [31mremotes/origin/dev/normalization/network_yuval[m
  [31mremotes/origin/dev/normalization/parameters/dns[m
  [31mremotes/origin/dev/normalization/process[m
  [31mremotes/origin/dev/normalization/process_analytics[m
  [31mremotes/origin/dev/viskumar/enableFusionDefault[m
  [31mremotes/origin/dicolanl-39[m
  [31mremotes/origin/dicolanl-44[m
  [31mremotes/origin/dicolanl-45[m
  [31mremotes/origin/dicolanl-49[m
  [31mremotes/origin/dicolanl-53[m
  [31mremotes/origin/dicolanl-57[m
  [31mremotes/origin/dicolanl-58[m
  [31mremotes/origin/dicolanl-59[m
  [31mremotes/origin/dicolanl-60[m
  [31mremotes/origin/dicolanl-61[m
  [31mremotes/origin/dicolanl-62[m
  [31mremotes/origin/dicolanl-63[m
  [31mremotes/origin/dicolanl-64[m
  [31mremotes/origin/dicolanl-65[m
  [31mremotes/origin/dicolanl-66[m
  [31mremotes/origin/dicolanl-67[m
  [31mremotes/origin/dicolanl-68[m
  [31mremotes/origin/dicolanl-69[m
  [31mremotes/origin/dicolanl-70[m
  [31mremotes/origin/dicolanl-71[m
  [31mremotes/origin/dicolanl-72[m
  [31mremotes/origin/dicolanl-73[m
  [31mremotes/origin/duoconnector[m
  [31mremotes/origin/duoconnector2[m
  [31mremotes/origin/featue/v-ampami/SentinelOneLogging[m
  [31mremotes/origin/feature/ambergma/improveTest[m
  [31mremotes/origin/feature/lahisham/updateKustoServices[m
  [31mremotes/origin/feature/lahisham/updateKustoServicesNuget[m
  [31mremotes/origin/feature/t-shfeli/AddDummyNrtTemplates[m
  [31mremotes/origin/feature/t-shfeli/AddingScheduledKindToAllExisitngTemplates[m
  [31mremotes/origin/feature/t-shfeli/addKindToAllExistingTemplates[m
  [31mremotes/origin/feature/v-admahe/AddLineNumberInError[m
  [31mremotes/origin/feature/v-admahe/CiscoASAPlaybook[m
  [31mremotes/origin/feature/v-admahe/CognniStatusUpdate[m
  [31mremotes/origin/feature/v-admahe/CrowdStrikeFDRMoveFileForSolution[m
  [31mremotes/origin/feature/v-admahe/FortinetPlaybook[m
  [31mremotes/origin/feature/v-admahe/HYASPlaybook[m
  [31mremotes/origin/feature/v-admahe/Pr-969[m
  [31mremotes/origin/feature/v-admahe/ProofPointTapSolution[m
  [31mremotes/origin/feature/v-admahe/ReversingLabsPlaybook[m
  [31mremotes/origin/feature/v-admahe/RiskIQPlaybook[m
  [31mremotes/origin/feature/v-admahe/RiskIQV2Playbook[m
  [31mremotes/origin/feature/v-admahe/SampleDataValidation[m
  [31mremotes/origin/feature/v-admahe/incident_24695978_ICM[m
  [31mremotes/origin/feature/v-admahe/paloaltoPANPlaybook[m
  [31mremotes/origin/feature/v-ampami/CiscoUmbrellaLogging[m
  [31mremotes/origin/feature/v-ampami/CiscoUmbrellaSolution[m
  [31mremotes/origin/feature/v-ampami/CrowdStrike[m
  [31mremotes/origin/feature/v-ampami/InfobloxCloudDataConnector[m
  [31mremotes/origin/feature/v-ampami/KPNucleusMovetoSolution[m
  [31mremotes/origin/feature/v-ampami/QualysKBLogging[m
  [31mremotes/origin/feature/v-ampami/ReadmeDocumentation[m
  [31mremotes/origin/feature/v-ampami/TrendMicroLogging[m
  [31mremotes/origin/feature/v-ampami/ciscoISEPackage[m
  [31mremotes/origin/feature/v-maudan/OktGovCodeChanges[m
  [31mremotes/origin/feature/v-rucdu/MetadataChanges[m
  [31mremotes/origin/feature/v-rucdu/SkipTemplatesFolder[m
  [31mremotes/origin/feauture/v-ampami/InfobloxCloudDataConnectorSolution[m
  [31mremotes/origin/feauture/v-ampami/McAfeeePOtextUpdate[m
  [31mremotes/origin/feauture/v-ampami/MoveOracleDBtoSolution[m
  [31mremotes/origin/fix-DEV-0322_SolarWinds_Serv-U_IOC-entitymapping[m
  [31mremotes/origin/fixDuoIssue[m
  [31mremotes/origin/ifeo-fix[m
  [31mremotes/origin/insights_preview[m
  [31mremotes/origin/liatlishams-patch-1[m
  [31mremotes/origin/liatlishams-patch-2[m
  [31mremotes/origin/link-AKS-workbook-to-the-connector[m
  [31mremotes/origin/lior-tamir[m
  [31mremotes/origin/lior-tamir-patch-1[m
  [31mremotes/origin/lior-tamir-patch-4[m
  [31mremotes/origin/lior-tamir-patch-5[m
  [31mremotes/origin/lior-tamir-patch-6[m
  [31mremotes/origin/lior-tamir-patch-7[m
  [31mremotes/origin/maayan-azure-resource-activities[m
  [31mremotes/origin/master[m
  [31mremotes/origin/mitre-attack-solution[m
  [31mremotes/origin/mohitkusecurity/NetSec-Azure-Sentinel[m
  [31mremotes/origin/morshabi-patch-50[m
  [31mremotes/origin/nazang/feature/govOkta[m
  [31mremotes/origin/pebryan/2021-09-20_AADSecOps[m
  [31mremotes/origin/pebryan/2021-8-25_LegacyAuthFix[m
  [31mremotes/origin/pebryan/2021-8-2_EWS[m
  [31mremotes/origin/pebryan/2021-8-9_Watchlists[m
  [31mremotes/origin/pfsense[m
  [31mremotes/origin/playbooksGallery[m
  [31mremotes/origin/revert-2614-ifeo-fix[m
  [31mremotes/origin/revert-3000-dev/normalization/network_v2_reboot[m
  [31mremotes/origin/sarah-yo-patch-1[m
  [31mremotes/origin/sarah-yo-patch-2[m
  [31mremotes/origin/sentinelIoTUpsellWorkbook[m
  [31mremotes/origin/sentinelIoTUpsellworkbookupdate[m
  [31mremotes/origin/sentinetlIoTUpsellUpdate[m
  [31mremotes/origin/shainw-ARG1[m
  [31mremotes/origin/shainw-ARG2[m
  [31mremotes/origin/shainw-NumResFix[m
  [31mremotes/origin/shainw-imDnsWorkAround[m
  [31mremotes/origin/shainw-patch-1[m
  [31mremotes/origin/shainw-patch-2[m
  [31mremotes/origin/shainw-patch-3[m
  [31mremotes/origin/shschwar/update-code-owners[m
  [31mremotes/origin/signinlogsquery-fix[m
  [31mremotes/origin/t-shaviv-patch-1[m
  [31mremotes/origin/t-shaviv-patch-2[m
  [31mremotes/origin/t-shaviv-patch-3[m
  [31mremotes/origin/t-shaviv-patch-4[m
  [31mremotes/origin/t-shaviv-patch-5[m
  [31mremotes/origin/t-shaviv-patch-6[m
  [31mremotes/origin/t-shfeli/addSupportForNrtTemplates[m
  [31mremotes/origin/tatecksi-patch-1[m
  [31mremotes/origin/testBranch[m
  [31mremotes/origin/testBranch12[m
  [31mremotes/origin/testBranch2[m
  [31mremotes/origin/testbranch[m
  [31mremotes/origin/thbanasi-CMMCSolution[m
  [31mremotes/origin/thbanasi-CMMCSolution-2[m
  [31mremotes/origin/thbanasi-CMMCSolution_Workbook&Analytics[m
  [31mremotes/origin/thbanasi-IRM3[m
  [31mremotes/origin/thbanasi-IRMSurvey[m
  [31mremotes/origin/thbanasi-IRMSurveyUpdate[m
  [31mremotes/origin/thbanasi-InsiderRiskManagement3[m
  [31mremotes/origin/thbanasi-MITREATT&CK[m
  [31mremotes/origin/thbanasi-MITRESurveyUpdate[m
  [31mremotes/origin/thbanasi-ZeroTrust[m
  [31mremotes/origin/thbanasi-ZeroTrustSurvey[m
  [31mremotes/origin/thbanasi-branch5[m
  [31mremotes/origin/thbanasi-cmmc3[m
  [31mremotes/origin/thbanasi-cmmc4[m
  [31mremotes/origin/thbanasi-cmmc5[m
  [31mremotes/origin/thbanasi-cmmc6[m
  [31mremotes/origin/thbanasi-insiderriskmanagement2[m
  [31mremotes/origin/thbanasi-patch-1[m
  [31mremotes/origin/thbanasi-patch-10[m
  [31mremotes/origin/thbanasi-patch-11[m
  [31mremotes/origin/thbanasi-patch-12[m
  [31mremotes/origin/thbanasi-patch-5[m
  [31mremotes/origin/thbanasi-patch-6[m
  [31mremotes/origin/thbanasi_IRM4[m
  [31mremotes/origin/thbanasi_IRM5[m
  [31mremotes/origin/updateNuget[m
  [31mremotes/origin/usageWorkbook[m
  [31mremotes/origin/v-ampami/QualysVMV2[m
  [31mremotes/origin/v-ampami/additionalBannerTextChange[m
  [31mremotes/origin/v-ampami/feature/Agaritest[m
  [31mremotes/origin/v-jayakal-CiscoUmbrella-Solutions[m
  [31mremotes/origin/v-jayakal-PublisherChange[m
  [31mremotes/origin/v-jayakal-patch-10[m
  [31mremotes/origin/v-maudan-patch-1[m
  [31mremotes/origin/v-maudan-patch-2[m
  [31mremotes/origin/v-maudan-patch-3[m
  [31mremotes/origin/v-maudan/-TenableIOPkgFix[m
  [31mremotes/origin/v-maudan/AdditionalLoggingProofpointPOD[m
  [31mremotes/origin/v-maudan/AdditionalLoggingcarbonBlackAzFun[m
  [31mremotes/origin/v-maudan/AzureFunctionQualysVM_V2[m
  [31mremotes/origin/v-maudan/CarbonBlackPagination[m
  [31mremotes/origin/v-maudan/CarbonBlackPaginationEvents[m
  [31mremotes/origin/v-maudan/CiscoASAPlaybook[m
  [31mremotes/origin/v-maudan/CiscoASA_CopyToSolutionFolder[m
  [31mremotes/origin/v-maudan/CiscoUmbrealla_VersionUpdate[m
  [31mremotes/origin/v-maudan/CiscoUmbrellaSolution[m
  [31mremotes/origin/v-maudan/CiscoUmbrellaSolutionSolution[m
  [31mremotes/origin/v-maudan/CisoISElinkupdate[m
  [31mremotes/origin/v-maudan/Cloudflare_To_Solution[m
  [31mremotes/origin/v-maudan/CopyToSolution_FortinetFortiGate[m
  [31mremotes/origin/v-maudan/CopyToSolution_PaloAlto_PAN_OS[m
  [31mremotes/origin/v-maudan/Corelight_To_Solution[m
  [31mremotes/origin/v-maudan/ESETEnterprise_GovChanges[m
  [31mremotes/origin/v-maudan/ESETenterprise[m
  [31mremotes/origin/v-maudan/ExtendDetectionValidationToSolution[m
  [31mremotes/origin/v-maudan/GCPDNS_ParserRename[m
  [31mremotes/origin/v-maudan/GWorkspaceConnector_issueFix[m
  [31mremotes/origin/v-maudan/GoogleWorkspaceReports_InstructionUpdate[m
  [31mremotes/origin/v-maudan/GroupIB_Playbooks_To_Solution[m
  [31mremotes/origin/v-maudan/JiraAudit_GovChanges[m
  [31mremotes/origin/v-maudan/KQLDetectionValidationToSolution[m
  [31mremotes/origin/v-maudan/McAfeeePO_To_Solution[m
  [31mremotes/origin/v-maudan/MoveParserCrowdstrikeFalconEventStream_TOSolution[m
  [31mremotes/origin/v-maudan/ProofpointPOD_GovChanges[m
  [31mremotes/origin/v-maudan/ProofpointTapFixDeploymentlink[m
  [31mremotes/origin/v-maudan/QualysVMFix[m
  [31mremotes/origin/v-maudan/QualysVM_V2[m
  [31mremotes/origin/v-maudan/RegionTest[m
  [31mremotes/origin/v-maudan/Rename_Ubiquitiparser[m
  [31mremotes/origin/v-maudan/SalesforceTokenUriIssue[m
  [31mremotes/origin/v-maudan/SampleDataIngestToolupdateV1[m
  [31mremotes/origin/v-maudan/SlackAudit_GovChanges[m
  [31mremotes/origin/v-maudan/TelementryTest[m
  [31mremotes/origin/v-maudan/TenableIOPythonPkg[m
  [31mremotes/origin/v-maudan/TenableNessusUpdates[m
  [31mremotes/origin/v-maudan/TestOktaMoreLogging[m
  [31mremotes/origin/v-maudan/TestProofPointTAP[m
  [31mremotes/origin/v-maudan/azureDeployTemplateChange[m
  [31mremotes/origin/v-maudan/box_GovChanges[m
  [31mremotes/origin/v-maudan/carbanBlack_VersboseLogging[m
  [31mremotes/origin/v-maudan/carbanBlack_VersboseLoggingNoHostChanges[m
  [31mremotes/origin/v-maudan/carbonBlackAzureFunction[m
  [31mremotes/origin/v-maudan/moreLoggingcarbonBlackAzFun[m
  [31mremotes/origin/v-maudan/paloAltoPanOs-SolutionPackageUpdate[m
  [31mremotes/origin/v-maudan/paloaltoPANPlaybook[m
  [31mremotes/origin/v-maudan/vArmourPackageUpdate[m
  [31mremotes/origin/v-muadan/TraningLabUpdate[m
  [31mremotes/origin/v-mudan/FortinetPlaybook[m
  [31mremotes/origin/v-ntripathi/PaloAltoNetworks(Firewall)[m
  [31mremotes/origin/v-ntripathi/SampleDataAndEmailIdValidationTest[m
  [31mremotes/origin/v-ntripathi/ZeroTrust(TIC3.0)Revised[m
  [31mremotes/origin/v-ntripathi/armorbloxTest[m
  [31mremotes/origin/v-ntripathi/testBranchVerifyValidationChecks[m
  [31mremotes/origin/v-ntripathi/validationOfSampleData[m
  [31mremotes/origin/v-rucdu-DummySampleDataValidationBranch[m
  [31mremotes/origin/v-rucdu-DummySampleDataValidationBranch-1[m
  [31mremotes/origin/v-rucdu-Duosceuritylogo[m
  [31mremotes/origin/v-rucdu-PRValidationVerification[m
  [31mremotes/origin/v-rucdu-oktasinglesignonVersion[m
  [31mremotes/origin/v-rucdu-oktasinglesignonVersion-1[m
  [31mremotes/origin/v-rucdu-oktasinglesignonVersion-2[m
  [31mremotes/origin/v-rucdu-oktasinglesignonVersion-3[m
  [31mremotes/origin/v-rucdu-patch-1[m
  [31mremotes/origin/v-rucdu-patch-3[m
  [31mremotes/origin/v-rucdu-patch-4[m
  [31mremotes/origin/v-rucdu-patch-6-1[m
  [31mremotes/origin/v-rucdu/AddFeatureFlagForWorkbook[m
  [31mremotes/origin/v-rucdu/AddUnifiSGWhitePreviewImageback[m
  [31mremotes/origin/v-rucdu/AddingProofpointTapWorkbook[m
  [31mremotes/origin/v-rucdu/AzureAuditActivityAndSigninWorkbookFix[m
  [31mremotes/origin/v-rucdu/AzureDDoSWorbookIssueFix[m
  [31mremotes/origin/v-rucdu/AzurePurviewValidationFixTestBranch[m
  [31mremotes/origin/v-rucdu/DarkTraceRevertChanges[m
  [31mremotes/origin/v-rucdu/DataConnectorDepeendencyUpdateInWorkbookMetadata[m
  [31mremotes/origin/v-rucdu/DataConnectorPRValidationFix[m
  [31mremotes/origin/v-rucdu/DummyPR[m
  [31mremotes/origin/v-rucdu/EnabledMemoryProfiler[m
  [31mremotes/origin/v-rucdu/EventConnectorTemplate[m
  [31mremotes/origin/v-rucdu/ExtendedWorkbookValidations[m
  [31mremotes/origin/v-rucdu/FixForPRValidations[m
  [31mremotes/origin/v-rucdu/FixForWorkbookLocalizationICM[m
  [31mremotes/origin/v-rucdu/FixTypoInO365Workbook[m
  [31mremotes/origin/v-rucdu/LogoValidationExtensionToSolutionsWorkbookFolder[m
  [31mremotes/origin/v-rucdu/NetskopeAdditionalLoggingForPostData[m
  [31mremotes/origin/v-rucdu/NetskopeAzureFunctionTimeoutValueExtended[m
  [31mremotes/origin/v-rucdu/PRValidationFix[m
  [31mremotes/origin/v-rucdu/PRValidationFixesForSolutionsFolder[m
  [31mremotes/origin/v-rucdu/PrivatePreviewWorkbook[m
  [31mremotes/origin/v-rucdu/SkipConnectorValidationForEventDataType[m
  [31mremotes/origin/v-rucdu/SolutionToolUpdate[m
  [31mremotes/origin/v-rucdu/TestingValidationsForSolutions[m
  [31mremotes/origin/v-rucdu/UpdateAdvancedSettings[m
  [31mremotes/origin/v-rucdu/UpdateBetterMTDWorkbookVersion[m
  [31mremotes/origin/v-rucdu/VMwareEventsApiMigration[m
  [31mremotes/origin/v-rucdu/ValidationTestBranch[m
  [31mremotes/origin/v-rucdu/Workbo