schemaVersion: 1.0.0
tableMappings:
  Cloudflare: CloudflareV2_CL
functionMappings: {}
columnMappings:
  ClientIPClass: ClientIPClass
  ClientRequestURI: ClientRequestURI
  DstBytes: EdgeResponseBytes
  HttpRequestHeaderHost: ClientRequestHost
  HttpRequestMethod: ClientRequestMethod
  HttpStatusCode: OriginResponseStatus
  HttpUserAgentOriginal: ClientRequestUserAgent
  SrcBytes: ClientRequestBytes
  SrcGeoCountry: ClientCountry
  SrcIpAddr: ClientIP
  WAFAction: SecurityAction
  WAFRuleID: SecurityRuleID
  WAFRuleMessage: SecurityRuleDescription
ruleOverrides:
  7313352a-09f6-4a84-88bd-6f17f1cbeb88:
    tactic: Persistence
    techniques:
      - T1505
