from enum import Enum
from typing import Optional

from pydantic import BaseModel


class RiskLevel(str, Enum):
    UNDEFINED = 'undefined'
    INFO = 'info'
    LOW = 'low'
    MEDIUM = 'medium'
    HIGH = 'high'
    CRITICAL = 'critical'


class OATTaskMessage(BaseModel):
    clp_id: str
    token: Optional[str]
    start_time: str
    end_time: str
    task_id: Optional[str]


class OATFileMessage(BaseModel):
    clp_id: str
    token: Optional[str]
    package_id: str
    task_id: Optional[str]
    pipeline_id: str


ALLOWED_OAT_FIELDS = [
    "detectionTime",
    "endpoint",
    "filters",
    "entityType",
    "entityName",
]

ALLOWED_OAT_DETAIL_FIELDS = [
    "act",
    "actResult",
    "additionalEventData",
    "aggregatedCount",
    "app",
    "appDexSha256",
    "appGroup",
    "application",
    "aptRelated",
    "attachmentFileHash",
    "attachmentFileHashSha1",
    "attachmentFileHashSha256",
    "attachmentFileHashSha256s",
    "attachmentFileHashes",
    "attachmentFileHashs",
    "attachmentFileName",
    "attachmentFileSize",
    "attachmentFileTlshes",
    "attachmentFileTlshs",
    "attachmentFileType",
    "attachmentSha1",
    "attachmentSha256",
    "attachmentSize",
    "attachmentSource",
    "attachmentTlsh",
    "attachmentUrls",
    "behaviorCat",
    "blocking",
    "bmGroup",
    "botCmd",
    "botUrl",
    "cat",
    "cccaDestination",
    "cccaDestinationFormat",
    "cccaDetection",
    "cccaDetectionSource",
    "cccaRiskLevel",
    "channel",
    "clientFlag",
    "clientIp",
    "compressedFileHash",
    "compressedFileHashSha256",
    "compressedFileName",
    "compressedFileSize",
    "compressedFileType",
    "computerDomain",
    "confidence",
    "correlationCat",
    "correlationData",
    "cve",
    "cves",
    "dOSName",
    "dUser1",
    "data0",
    "data0Name",
    "data1",
    "data1Name",
    "data2",
    "dataType",
    "description",
    "destinationPath",
    "detailTrace",
    "detectionName",
    "detectionType",
    "deviceDirection",
    "deviceGUID",
    "deviceMacAddress",
    "dhost",
    "direction",
    "dmac",
    "dnsQueryType",
    "domainName",
    "dpt",
    "dst",
    "dstGroup",
    "dstZone",
    "duser",
    "dvchost",
    "endpointGUID",
    "endpointGuid",
    "endpointHostName",
    "endpointIp",
    "endpointMacAddress",
    "endpointModel",
    "engineOperation",
    "errorMessage",
    "eventClass",
    "eventDataAuthenticationPackageName",
    "eventDataConsumer",
    "eventDataIpAddress",
    "eventDataLogonProcessName",
    "eventDataLogonType",
    "eventDataPath",
    "eventDataProviderName",
    "eventDataProviderPath",
    "eventDataScriptBlockText",
    "eventID",
    "eventId",
    "eventName",
    "eventSourceType",
    "eventSubClass",
    "eventSubId",
    "eventSubName",
    "eventTime",
    "extraInfo",
    "fileCreation",
    "fileExt",
    "fileHash",
    "fileHashSha256",
    "fileName",
    "fileOperation",
    "filePath",
    "filePathName",
    "fileSize",
    "fileType",
    "filterName",
    "filterRiskLevel",
    "filterType",
    "firstAct",
    "firstActResult",
    "firstSeen",
    "forensicFileHash",
    "forensicFilePath",
    "fullPath",
    "highlightedText",
    "hostName",
    "hostSeverity",
    "hotFix",
    "httpLocation",
    "httpReferer",
    "httpXForwardedForIp",
    "interestedGroup",
    "interestedHost",
    "interestedIp",
    "interestedMacAddress",
    "ircChannelName",
    "ja3Hash",
    "ja3sHash",
    "k8sNamespace",
    "lastSeen",
    "logonUser",
    "mDevice",
    "mailAttachmentHash",
    "mailBccAddresses",
    "mailCcAddresses",
    "mailDeliveryTime",
    "mailDirection",
    "mailFolder",
    "mailFromAddresses",
    "mailHeaderHash",
    "mailHelo",
    "mailMetaData",
    "mailMetaText",
    "mailMsgSubject",
    "mailReceivedTime",
    "mailReplyToAddresses",
    "mailRuleId",
    "mailScore",
    "mailSenderIp",
    "mailSmtpFromAddresses",
    "mailSmtpOriginalRecipients",
    "mailSmtpRecipients",
    "mailSourceDomain",
    "mailTagHash",
    "mailTagHashRawSignature",
    "mailTextHash",
    "mailThreatType",
    "mailToAddresses",
    "mailUrlHash",
    "mailUrlsRealLink",
    "mailUrlsVisibleLink",
    "mailUserAgent",
    "mailWholeHeader",
    "mailXMailer",
    "mailbox",
    "malDst",
    "malFamily",
    "malName",
    "malSrc",
    "malSubType",
    "malType",
    "malTypeGroup",
    "metaPwdSprayClientAppUsed",
    "metaPwdSprayClientDeviceBrowser",
    "metaPwdSprayIp",
    "metaPwdSprayIpSignInFailCount",
    "metaPwdSprayIpSignInSuccessCount",
    "metaPwdSprayIpUserCount",
    "metaPwdSprayUserSignInFailCount",
    "metaPwdSprayUserSignInSuccessCount",
    "metaSuspiciousMailboxRulesForwardAddresses",
    "metaType",
    "mitreMapping",
    "moduleName",
    "msgUuidChain",
    "objectApiHookNum",
    "objectApiName",
    "objectAppName",
    "objectBmData",
    "objectCmd",
    "objectCmdNormalized",
    "objectContentName",
    "objectFileCreation",
    "objectFileGroupName",
    "objectFileHashSha1",
    "objectFileHashSha256",
    "objectFileIsRemoteAccess",
    "objectFileModifiedTime",
    "objectFileName",
    "objectFileOwnerSid",
    "objectFilePath",
    "objectFileRemoteAccess",
    "objectFileSaclString",
    "objectFileSize",
    "objectFirstRecorded",
    "objectFirstSeen",
    "objectHostName",
    "objectIp",
    "objectIps",
    "objectLastSeen",
    "objectLaunchTime",
    "objectName",
    "objectPort",
    "objectRawDataStr",
    "objectRegType",
    "objectRegistryData",
    "objectRegistryKeyHandle",
    "objectRegistryRoot",
    "objectRegistryValue",
    "objectRunAsLocalAccount",
    "objectSigner",
    "objectSignerValid",
    "objectSubTrueType",
    "objectTrueType",
    "objectType",
    "objectUser",
    "objectUserDomain",
    "objectUserGroup",
    "osName",
    "osType",
    "osVer",
    "pAttackPhase",
    "pComp",
    "pTags",
    "parentCmd",
    "parentCmdNormalized",
    "parentFileCreation",
    "parentFileGroupName",
    "parentFileHashSha1",
    "parentFileHashSha256",
    "parentFileModifiedTime",
    "parentFilePath",
    "parentFileRemoteAccess",
    "parentFileSize",
    "parentLaunchTime",
    "parentName",
    "parentSigner",
    "parentSignerValid",
    "parentSubTrueType",
    "parentTrueType",
    "parentUser",
    "parentUserDomain",
    "pcapUUID",
    "peerGroup",
    "peerHost",
    "peerIp",
    "plang",
    "pname",
    "policyId",
    "policyName",
    "policyTemplate",
    "policyUuid",
    "principalName",
    "processCmd",
    "processCmdNormalized",
    "processFileCreation",
    "processFileGroupName",
    "processFileHashSha1",
    "processFileHashSha256",
    "processFileModifiedTime",
    "processFilePath",
    "processFileRemoteAccess",
    "processFileSaclString",
    "processFileSize",
    "processLaunchTime",
    "processName",
    "processPid",
    "processSigner",
    "processSignerValid",
    "processSubTrueType",
    "processTrueType",
    "processUser",
    "processUserDomain",
    "proto",
    "rating",
    "rawDataStr",
    "rawDstIp",
    "rawDstPort",
    "remarks",
    "request",
    "requestBase",
    "requestClientApplication",
    "requestHeaders",
    "requests",
    "riskConfidenceLevel",
    "riskLevel",
    "rt",
    "rtHour",
    "ruleId",
    "ruleName",
    "ruleSetName",
    "ruleType",
    "ruleVer",
    "sAttackPhase",
    "sOSName",
    "sUser1",
    "samUser",
    "scanTs",
    "scanType",
    "score",
    "secondAct",
    "secondActResult",
    "sender",
    "senderIp",
    "severity",
    "shost",
    "signInHighlightAppNames",
    "signInHighlightEventTimestamps",
    "signInHighlightIps",
    "signer",
    "smac",
    "smbSharedName",
    "spt",
    "src",
    "srcFileCreation",
    "srcFileCurrentOwnerName",
    "srcFileGroupName",
    "srcFileHashSha1",
    "srcFileHashSha256",
    "srcFileIsRemoteAccess",
    "srcFileModifiedTime",
    "srcFileOwnerName",
    "srcFilePath",
    "srcFileSize",
    "srcFirstSeen",
    "srcGroup",
    "srcLastSeen",
    "srcSigner",
    "srcSignerValid",
    "srcZone",
    "subRuleId",
    "subRuleName",
    "suid",
    "suser",
    "suspiciousObject",
    "suspiciousObjectType",
    "tacticId",
    "tags",
    "targetShare",
    "targetType",
    "threatName",
    "threatType",
    "timezone",
    "urlCat",
    "userDepartment",
    "userDomain",
    "uuid",
    "winEventId"
]

OAT_OVERSIZED_FIELDS = [
    ["detail", "objectRegistryData"],
    ["detail", "objectRawDataStr"],
    ["detail", "rawDataStr"],
    ["detail", "remarks"],
    ["detail", "requests"],
    ["detail", "mailToAddresses"],
    ["detail", "mailUrlsVisibleLink"],
    ["detail", "mailUrlsRealLink"],
    ["detail", "mailTagHashRawSignature"],
    ["filters"]
]
