id: 0aded97e-4e2d-4e4d-93cf-4a7e45c7bab2
name: Recorded Future Playbook Alerts Incident Creation
description: |
  'Create Recorded Future Playbook Alerts in Microsoft Defender'
severity: Medium
status: Available
queryFrequency: 1h
queryPeriod: 1h
triggerOperator: gt
triggerThreshold: 0
tactics: []
relevantTechniques: []
requiredDataConnectors:
  - connectorId: RecordedFuture
    dataTypes:
      - RecordedFuturePlaybookAlerts_V2_CL
query: |
  RecordedFuturePlaybookAlerts_V2_CL
  | where TimeGenerated >= now(-1h)
eventGroupingSettings:
  aggregationKind: AlertPerResult
alertDetailsOverride:
  alertDisplayNameFormat: 'Alert: {{rule_label}}  - {{alert_title}}'
  alertDescriptionFormat: |
    _Recorded Future Alert_

    Evidence Summary:
    {{alert_description}}

    Priority: {{priority}}

    Recorded Future Playbook Alert ID
    {{id}}
  alertDynamicProperties:
    - alertProperty: AlertLink
      value: link
customDetails:
  Category: category
incidentConfiguration:
  createIncident: true
  groupingConfiguration:
    enabled: true
    reopenClosedIncident: false
    lookbackDuration: 1h
    matchingMethod: Selected
    groupByCustomDetails:
      - Category
version: 2.0.0
kind: NRT
