id: "[concat(resourceId('Microsoft.OperationalInsights/workspaces/providers', parameters('workspace'), 'Microsoft.SecurityInsights'),'/alertRules/c2bac1d4-3664-4985-b3e5-d16b6d1c52b1')]"
name: "[concat(parameters('workspace'),'/Microsoft.SecurityInsights/c2bac1d4-3664-4985-b3e5-d16b6d1c52b1')]"
type: Microsoft.OperationalInsights/workspaces/providers/alertRules
kind: NRT
apiVersion: 2023-12-01-preview
properties:
  displayName: Removable Storage ONLINE
  description: Detect when a removable storage device is plugged in by the end-user.
  severity: High
  enabled: true
  query: |+
    secRMM_CL | where Event_s == "ONLINE" | 
    extend AccountCustomEntity = User_s |
    extend HostCustomEntity = Computer
  suppressionDuration: PT5H
  suppressionEnabled: false
  tactics:
  - Collection
  techniques:
  - T1025
  subTechniques: []
  alertRuleTemplateName: 
  incidentConfiguration:
    createIncident: true
    groupingConfiguration:
      enabled: false
      reopenClosedIncident: false
      lookbackDuration: PT5H
      matchingMethod: AllEntities
      groupByEntities: []
      groupByAlertDetails: []
      groupByCustomDetails: []
  eventGroupingSettings:
    aggregationKind: AlertPerResult
  alertDetailsOverride: 
  customDetails: 
  entityMappings:
  - entityType: Account
    fieldMappings:
    - identifier: AadUserId
      columnName: User_s
  - entityType: Host
    fieldMappings:
    - identifier: HostName
      columnName: Computer
  sentinelEntitiesMappings: 
  templateVersion: 
