id: A22B2ECF-1478-4400-877E-07A32E53A897
name: Removable storage ONLINE event from secRMM
description: Detect when a removable storage device is plugged in by the end-user.
severity: High
kind: NRT
apiVersion: 2023-12-01-preview
displayName: Removable Storage ONLINE
enabled: true
query: |+
    secRMM_CL | where Event_s == "ONLINE" | 
    extend AccountCustomEntity = User_s |
    extend HostCustomEntity = Computer
suppressionDuration: PT5H
suppressionEnabled: false
tactics:
- Collection
techniques:
- T1025
subTechniques: []
alertRuleTemplateName: 
incidentConfiguration:
createIncident: true
groupingConfiguration:
    enabled: false
    reopenClosedIncident: false
    lookbackDuration: PT5H
    matchingMethod: AllEntities
    groupByEntities: []
    groupByAlertDetails: []
    groupByCustomDetails: []
eventGroupingSettings:
aggregationKind: AlertPerResult
alertDetailsOverride: 
customDetails: 
entityMappings:
- entityType: Account
  fieldMappings:
    - identifier: AadUserId
      columnName: User_s
- entityType: Host
  fieldMappings:
    - identifier: HostName
      columnName: Computer
