id: 8efb258d-1987-4add-8fab-df6cb2e7886c
name: Application Granted EWS Permissions
description: |
  'As part of content migration, this file is moved to new location. you can find here: https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Cloud%20Identity%20Threat%20Protection%20Essentials/Hunting%20Queries/ApplicationGrantedEWSPermissions.yaml'
