id: cefd7f18-9359-4a99-bd18-965983bb724d
name: SlackAudit - Applications installed
description: This hunt searches for Slack application installation events to identify potentially unauthorized or suspicious
  app installs by users.
requiredDataConnectors:
- connectorId: SlackAuditAPI
  dataTypes:
  - SlackAudit_CL
tactics:
- InitialAccess
- Persistence
relevantTechniques:
- T1133
- T1098.003
query: |-
  SlackAudit
  | where TimeGenerated > ago(24h)
  | where DvcAction =~ 'app_installed'
  | summarize by SrcUserName, EntityAppName
  | extend AccountCustomEntity = SrcUserName
entityMappings:
- entityType: Account
  fieldMappings:
  - identifier: FullName
    columnName: AccountCustomEntity