id: d6de1625-8d18-44da-9991-fbdc607b7643
name: Cross-tenant Access Settings Organization Outbound Direct Settings Changed
description: |
  'As part of content migration, this file is moved to a new location. You can find it here https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Microsoft%20Entra%20ID/Analytic%20Rules/Cross-tenantAccessSettingsOrganizationOutboundDirectSettingsChanged.yaml'
version: 1.0.3
kind: Scheduled
