id: c2da132e-6c27-4f50-9e40-f684ca94e5b2
name: Cross-tenant Access Settings Organization Deleted
description: |
  'As part of content migration, this file is moved to a new location. You can find it here https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Microsoft%20Entra%20ID/Analytic%20Rules/Cross-tenantAccessSettingsOrganizationDeleted.yaml'
version: 1.0.3
kind: Scheduled
