id: 7d44c4a7-f4a4-4f48-bd37-be333951a131
name: Cross-tenant Access Settings Organization Outbound Collaboration Settings Changed
description: |
  'As part of content migration, this file is moved to a new location. You can find it here https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Microsoft%20Entra%20ID/Analytic%20Rules/Cross-tenantAccessSettingsOrganizationOutboundCollaborationSettingsChanged.yaml'
version: 1.0.3
kind: Scheduled
