id: d1b60e24-4f06-4bed-af66-275e13fe7182
name: Cross-tenant Access Settings Organization Inbound Collaboration Settings Changed
description: |
  'As part of content migration, this file is moved to a new location. You can find it here https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Microsoft%20Entra%20ID/Analytic%20Rules/Cross-tenantAccessSettingsOrganizationInboundCollaborationSettingsChanged.yaml'
version: 1.0.3
kind: Scheduled
