// Code generated by mockery v2.49.1. DO NOT EDIT.

package sentinel

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// MockManager is an autogenerated mock type for the Manager type
type MockManager struct {
	mock.Mock
}

type MockManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManager) EXPECT() *MockManager_Expecter {
	return &MockManager_Expecter{mock: &_m.Mock}
}

// Upload provides a mock function with given fields: ctx, payload
func (_m *MockManager) Upload(ctx echo.Context, payload []byte) error {
	ret := _m.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context, []byte) error); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockManager_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockManager_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx echo.Context
//   - payload []byte
func (_e *MockManager_Expecter) Upload(ctx interface{}, payload interface{}) *MockManager_Upload_Call {
	return &MockManager_Upload_Call{Call: _e.mock.On("Upload", ctx, payload)}
}

func (_c *MockManager_Upload_Call) Run(run func(ctx echo.Context, payload []byte)) *MockManager_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context), args[1].([]byte))
	})
	return _c
}

func (_c *MockManager_Upload_Call) Return(_a0 error) *MockManager_Upload_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockManager_Upload_Call) RunAndReturn(run func(echo.Context, []byte) error) *MockManager_Upload_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockManager creates a new instance of MockManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManager {
	mock := &MockManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
