id: 84d4ecf3-64e0-4c38-9dab-9dafda4c576d
Function:
  Title: Parser for EventsApplication
  Version: "1.0.0"
  LastUpdated: "2024-03-06"
Category: Microsoft Sentinel Parser
FunctionName: EventsApplication
FunctionAlias: EventsApplication
FunctionQuery: |
  let Event_Application_View = view (){
      eventsapplicationdata_CL
      | extend 
          Category = column_ifexists('Category', ''),
          Computer = column_ifexists('Computer', ''),
          MG = column_ifexists('MG', ''),
          ManagementGroupName = column_ifexists('ManagementGroupName', ''),
          RawData = column_ifexists('RawData', ''),
          SourceSystem = column_ifexists('SourceSystem', ''),
          TenantId = column_ifexists('TenantId', ''),
          TimeGenerated  = column_ifexists('TimeGenerated', ''),
          Type = column_ifexists('Type', ''),
          _ResourceId = column_ifexists('_ResourceId', ''),
          Id = column_ifexists('_id_s', ''),
          AccessMethod = column_ifexists('access_method_s', ''),
          Action = column_ifexists('action_s', ''),
          Activity = column_ifexists('activity_s', ''),
          Alert = column_ifexists('alert_s', ''),
          AlertType = column_ifexists('alert_type_s', ''),
          AppActivity = column_ifexists('app_activity_s', ''),
          App = column_ifexists('app_s', ''),
          AppSessionId = column_ifexists('app_session_id_d', ''),
          AppCategory = column_ifexists('appcategory_s', ''),
          AppSuite = column_ifexists('appsuite_s', ''),
          audit_category = column_ifexists('audit_category_s', ''),
          audit_type = column_ifexists('audit_type_s', ''),
          Browser = column_ifexists('browser_s', ''),
          BrowserSessionId = column_ifexists('browser_session_id_d', ''),
          BrowserVersion = column_ifexists('browser_version_s', ''),
          CCI = column_ifexists('cci_d', ''),
          CCIString = column_ifexists('cci_s', ''),
          CCL = column_ifexists('ccl_s', ''),
          ChannelId = column_ifexists('channel_id_s', ''),
          ClientBytes = column_ifexists('client_bytes_d', ''),
          ConnDuration = column_ifexists('conn_duration_d', ''),
          ConnectionId = column_ifexists('connection_id_d', ''),
          Count = column_ifexists('count_d', ''),
          CononicalName = column_ifexists('CononicalName_s', ''),
          Custom_Connector = column_ifexists('custom_connector_s', ''),
          DataCenter = column_ifexists('data_center_s', ''),
          DataType = column_ifexists('data_type_s', ''),
          DeviceClassification = column_ifexists('device_classification_s', ''),
          Device = column_ifexists('device_s', ''),
          DlpFile = column_ifexists('dlp_file_s', ''),
          DlpIncidentId = column_ifexists('dlp_incident_id_d', ''),
          DlpIsUniqueCount = column_ifexists('dlp_is_unique_count_s', ''),
          DlpMailParentId = column_ifexists('dlp_mail_parent_id_s', ''),
          DlpParentId = column_ifexists('dlp_parent_id_d', ''),
          DlpProfile = column_ifexists('dlp_profile_s', ''),
          DlpRule = column_ifexists('dlp_rule_s', ''),
          DlpRuleCount = column_ifexists('dlp_rule_count_d', ''),
          DlpRuleSeverity = column_ifexists('dlp_rule_severity_s', ''),
          DlpUniquwCount = column_ifexists('dlp_unique_count_d', ''),
          DestinationCountry = column_ifexists('dst_country_s', ''),
          DestinationGeoipSource = column_ifexists('dst_geoip_src_d', ''),
          DestinationLatitude = column_ifexists('dst_latitude_d', ''),
          DestinationLocation = column_ifexists('dst_location_s', ''),
          DestinationLongitude = column_ifexists('dst_longitude_d', ''),
          DestinationRegion = column_ifexists('dst_region_s', ''),
          DestinationTimezone = column_ifexists('dst_timezone_s', ''),
          DestinationZipcode = column_ifexists('dst_zipcode_s', ''),
          DestinationHost = column_ifexists('dsthost_s', ''),
          DestinationIp = column_ifexists('dstip_s', ''),
          DestinationPort = column_ifexists('dstport_d', ''),
          Exposure = column_ifexists('exposure_s', ''),
          FileLang = column_ifexists('file_lang_s', ''),
          FilePath = column_ifexists('file_path_s', ''),
          FileSize = column_ifexists('file_size_d', ''),
          FileType = column_ifexists('file_type_s', ''),
          FromUserCategory = column_ifexists('from_user_category_s', ''),
          FromUser = column_ifexists('from_user_s', ''),
          Fromlogs = column_ifexists('fromlogs_s', ''),
          HostName = column_ifexists('hostname_s', ''),
          InstanceId = column_ifexists('instance_id_s', ''),
          Instance = column_ifexists('instance_s', ''),
          InternalCollaboratorCount = column_ifexists('internal_collaborator_count_d', ''),
          LogFileName = column_ifexists('log_file_name_s', ''),
          LoginType = column_ifexists('logintype_s', ''),
          LoginUrl = column_ifexists('loginurl_s', ''),
          ManagedApp = column_ifexists('managed_app_s', ''),
          ManagementId = column_ifexists('managementID_s', ''),
          Md5 = column_ifexists('md5_g', ''),
          MimeType = column_ifexists('mime_type_s', ''),
          Modified = column_ifexists('modified_d', ''),
          NetskopeActivity = column_ifexists('netskope_activity_s', ''),
          NetskopePop = column_ifexists('netskope_pop_s', ''),
          NotifyTemplate = column_ifexists('notify_template_s', ''),
          Nsdeviceuid = column_ifexists('nsdeviceuid_s', ''),
          Numbytes = column_ifexists('numbytes_d', ''),
          ObjectId = column_ifexists('object_id_s', ''),
          Object = column_ifexists('object_s', ''),
          ObjectType = column_ifexists('object_type_s', ''),
          Org = column_ifexists('org_s', ''),
          OrganizationUnit = column_ifexists('organization_unit_s', ''),
          OrignalFilePath = column_ifexists('orignal_file_path_s', ''),
          OS = column_ifexists('os_s', ''),
          OsVersion = column_ifexists('os_version_s', ''),
          OtherCategories = column_ifexists('other_categories_s', ''),
          Owner = column_ifexists('owner_s', ''),
          Page = column_ifexists('page_s', ''),
          PageSite = column_ifexists('page_site_s', ''),
          ParentId = column_ifexists('parent_id_s', ''),
          PolicyId = column_ifexists('policy_id_s', ''),
          Policy = column_ifexists('policy_s', ''),
          Protocol = column_ifexists('protocol_s', ''),
          Referer = column_ifexists('referer_s', ''),
          ReqCnt = column_ifexists('req_cnt_d', ''),
          RequestId = column_ifexists('request_id_s', ''),
          RespCnt = column_ifexists('resp_cnt_d', ''),
          SAMAccountName = column_ifexists('sAMAccountName_s', ''),
          sanctioned_instance = column_ifexists('sanctioned_instance_s', ''),
          ScanType = column_ifexists('scan_type_s', ''),
          Serial = column_ifexists('serial_s', ''),
          ServerBytes = column_ifexists('server_bytes_d', ''),
          SessionId = column_ifexists('sessionid_s', ''),
          Severity = column_ifexists('severity_s', ''),
          SHA256 = column_ifexists('sha256_s', ''),
          SharedWith = column_ifexists('shared_with_s', ''),
          Site = column_ifexists('site_s', ''),
          SmtpTo = column_ifexists('smtp_to_s', ''),
          SourceCountry = column_ifexists('src_country_s', ''),
          SourceGeoIpSrc = column_ifexists('src_geoip_src_d', ''),
          SourceLatitude = column_ifexists('src_latitude_d', ''),
          SourceLocation = column_ifexists('src_location_s', ''),
          SourceLongitude = column_ifexists('src_longitude_d', ''),
          SourceRegion = column_ifexists('src_region_s', ''),
          SourceTime = column_ifexists('src_time_s', ''),
          SourceTimezone = column_ifexists('src_timezone_s', ''),
          SourceZipcode = column_ifexists('src_zipcode_s', ''),
          SourceIp = column_ifexists('srcip_s', ''),
          SuppressionEndTime = column_ifexists('suppression_end_time_d', ''),
          SuppressionKey = column_ifexists('suppression_key_s', ''),
          SuppressionStartTime = column_ifexists('suppression_start_time_d', ''),
          TelemetryApp = column_ifexists('telemetry_app_s', ''),
          Timestamp = column_ifexists('timestamp_d', ''),
          Title = column_ifexists('title_s', ''),
          ToUser = column_ifexists('to_user_s', ''),
          TotalCollaboratorCount = column_ifexists('total_collaborator_count_d', ''),
          TrafficType = column_ifexists('traffic_type_s', ''),
          TransactionId = column_ifexists('transaction_id_d', ''),
          TrueObjCategory = column_ifexists('true_obj_category_s', ''),
          TrueObjType = column_ifexists('true_obj_type_s', ''),
          TssMode = column_ifexists('tss_mode_s', ''),
          PolicyType = column_ifexists('type_s', ''),
          UniversalConnector = column_ifexists('universal_connector_s', ''),
          UrNormalized = column_ifexists('ur_normalized_s', ''),
          Url = column_ifexists('url_s', ''),
          UserPrincipalName = column_ifexists('userPrincipalName_s', ''),
          UserCategory = column_ifexists('user_category_s', ''),
          UserId = column_ifexists('user_id_s', ''),
          User = column_ifexists('user_s', ''),
          Useragent = column_ifexists('useragent_s', ''),
          UserIp = column_ifexists('userip_s', ''),
          Userkey = column_ifexists('userkey_s', ''),
          WebUniversalConnector = column_ifexists('web_universal_connector_s', ''),
          WorkspaceId = column_ifexists('workspace_id_s', ''),
          Workspace = column_ifexists('workspace_s', '')
      |project 
          Category,
          Computer,
          MG,
          ManagementGroupName,
          RawData,
          SourceSystem,
          TenantId,
          TimeGenerated,
          Type,
          _ResourceId,
          Id,
          AccessMethod,
          Action,
          Activity,
          Alert,
          AlertType,
          AppActivity,
          App,
          AppSessionId,
          AppCategory,
          AppSuite,
          audit_category,
          audit_type,
          Browser,
          BrowserSessionId,
          BrowserVersion,
          CCI,
          CCIString,
          CCL,
          ChannelId,
          ClientBytes,
          ConnDuration,
          ConnectionId,
          Count,
          CononicalName,
          Custom_Connector,
          DataCenter,
          DataType,
          DeviceClassification,
          Device,
          DlpFile,
          DlpIncidentId,
          DlpIsUniqueCount,
          DlpMailParentId,
          DlpParentId,
          DlpProfile,
          DlpRule,
          DlpRuleCount,
          DlpRuleSeverity,
          DlpUniquwCount,
          DestinationCountry,
          DestinationGeoipSource,
          DestinationLatitude,
          DestinationLocation,
          DestinationLongitude,
          DestinationRegion,
          DestinationTimezone,
          DestinationZipcode,
          DestinationHost,
          DestinationIp,
          DestinationPort,
          Exposure,
          FileLang,
          FilePath,
          FileSize,
          FileType,
          FromUserCategory,
          FromUser,
          Fromlogs,
          HostName,
          InstanceId,
          Instance,
          InternalCollaboratorCount,
          LogFileName,
          LoginType,
          LoginUrl,
          ManagedApp,
          ManagementId,
          Md5,
          MimeType,
          Modified,
          NetskopeActivity,
          NetskopePop,
          NotifyTemplate,
          Nsdeviceuid,
          Numbytes,
          ObjectId,
          Object,
          ObjectType,
          Org,
          OrganizationUnit,
          OrignalFilePath,
          OS,
          OsVersion,
          OtherCategories,
          Owner,
          Page,
          PageSite,
          ParentId,
          PolicyId,
          Policy,
          Protocol,
          Referer,
          ReqCnt,
          RequestId,
          RespCnt,
          SAMAccountName,
          sanctioned_instance,
          ScanType,
          Serial,
          ServerBytes,
          SessionId,
          Severity,
          SHA256,
          SharedWith,
          Site,
          SmtpTo,
          SourceCountry,
          SourceGeoIpSrc,
          SourceLatitude,
          SourceLocation,
          SourceLongitude,
          SourceRegion,
          SourceTime,
          SourceTimezone,
          SourceZipcode,
          SourceIp,
          SuppressionEndTime,
          SuppressionKey,
          SuppressionStartTime,
          TelemetryApp,
          Timestamp,
          Title,
          ToUser,
          TotalCollaboratorCount,
          TrafficType,
          TransactionId,
          TrueObjCategory,
          TrueObjType,
          TssMode,
          PolicyType,
          UniversalConnector,
          UrNormalized,
          Url,
          UserPrincipalName,
          UserCategory,
          UserId,
          User,
          Useragent,
          UserIp,
          Userkey,
          WebUniversalConnector,
          WorkspaceId,
          Workspace
  };
  Event_Application_View