id: 57820420-5afe-49e6-8fdc-0a6b09e87f4a
Function:
  Title: Parser for Netskope Events Application
  Version: "1.0.0"
  LastUpdated: "2025-08-06"
Category: Microsoft Sentinel Parser
FunctionName: NetskopeEventsApplication
FunctionAlias: NetskopeEventsApplication
FunctionQuery: |
  let dummy_table = datatable(TimeGenerated: datetime) [];
  let NetskopeEventsApplication = view() {
    union isfuzzy=true dummy_table, NetskopeEventsApplication_CL
    | extend 
        TimeGenerated = column_ifexists('TimeGenerated', ''),
        AccessMethod = column_ifexists('access_method', ''),
        Action = column_ifexists('action', ''),
        Activity = column_ifexists('activity', ''),
        Alert = column_ifexists('alert', ''),
        AlertType = column_ifexists('alert_type', ''),
        App = column_ifexists('app', ''),
        AppActivity = column_ifexists('app_activity', ''),
        AppSessionId = column_ifexists('app_sessionid', ''),
        AppCategory = column_ifexists('appcategory', ''),
        AppSuite = column_ifexists('appsuite', ''),
        AuditCategory = column_ifexists('audit_category', ''),
        AuditType = column_ifexists('audit_type', ''),
        Browser = column_ifexists('browser', ''),
        BrowserSessionId = column_ifexists('browser_sessionid', ''),
        BrowserVersion = column_ifexists('browser_version', ''),
        Category = column_ifexists('category', ''),
        Cci = column_ifexists('cci', ''),
        Ccl = column_ifexists('ccl', ''),
        ChannelId = column_ifexists('channel_id', ''),
        ClientBytes = column_ifexists('client_bytes', ''),
        ConnDuration = column_ifexists('conn_duration', ''),
        ConnectionId = column_ifexists('connectionid', ''),
        CononicalName = column_ifexists('CononicalName', ''),
        CountI = column_ifexists('count_i', ''),
        CustomConnector = column_ifexists('custom_connector', ''),
        DataCenter = column_ifexists('data_center', ''),
        DataType = column_ifexists('data_type', ''),
        Device = column_ifexists('device', ''),
        DeviceClassification = column_ifexists('device_classification', ''),
        DlpFile = column_ifexists('dlp_file', ''),
        DlpIncidentId = column_ifexists('dlp_incidentid', ''),
        DlpIsUniqueCount = column_ifexists('dlp_is_unique_count', ''),
        DlpMailParentId = column_ifexists('dlp_mail_parent_id', ''),
        DlpParentId = column_ifexists('dlp_parentid', ''),
        DlpProfile = column_ifexists('dlp_profile', ''),
        DlpRule = column_ifexists('dlp_rule', ''),
        DlpRuleCount = column_ifexists('dlp_rule_count', ''),
        DlpRuleSeverity = column_ifexists('dlp_rule_severity', ''),
        DlpUniqueCount = column_ifexists('dlp_unique_count', ''),
        DstCountry = column_ifexists('dst_country', ''),
        DstGeoipSrc = column_ifexists('dst_geoip_src', ''),
        DstLatitude = column_ifexists('dst_latitude', ''),
        DstLocation = column_ifexists('dst_location', ''),
        DstLongitude = column_ifexists('dst_longitude', ''),
        DstRegion = column_ifexists('dst_region', ''),
        DstTimezone = column_ifexists('dst_timezone', ''),
        DstZipcode = column_ifexists('dst_zipcode', ''),
        DstHost = column_ifexists('dsthost', ''),
        DstIp = column_ifexists('dstip', ''),
        DstPort = column_ifexists('dstport', ''),
        Exposure = column_ifexists('exposure', ''),
        FileLang = column_ifexists('file_lang', ''),
        FilePath = column_ifexists('file_path', ''),
        FileSize = column_ifexists('file_size', ''),
        FileType = column_ifexists('file_type', ''),
        FromUser = column_ifexists('from_user', ''),
        FromUserCategory = column_ifexists('from_user_category', ''),
        FromLogs = column_ifexists('fromlogs', ''),
        HostName = column_ifexists('hostname', ''),
        Instance = column_ifexists('instance', ''),
        InstanceId = column_ifexists('instance_id', ''),
        InternalCollaboratorCount = column_ifexists('internal_collaborator_count', ''),
        LogFileName = column_ifexists('log_file_name', ''),
        LoginType = column_ifexists('logintype', ''),
        LoginUrl = column_ifexists('loginurl', ''),
        ManagedApp = column_ifexists('managed_app', ''),
        ManagementId = column_ifexists('managementID', ''),
        Md5 = column_ifexists('md5', ''),
        MimeType = column_ifexists('mime_type', ''),
        Modified = column_ifexists('modified', ''),
        NetskopeActivity = column_ifexists('netskope_activity', ''),
        NetskopePop = column_ifexists('netskope_pop', ''),
        NotifyTemplate = column_ifexists('notify_template', ''),
        NsDeviceUid = column_ifexists('nsdeviceuid', ''),
        NumBytes = column_ifexists('numbytes', ''),
        Object = column_ifexists('object', ''),
        ObjectId = column_ifexists('object_id', ''),
        ObjectType = column_ifexists('object_type', ''),
        Org = column_ifexists('org', ''),
        OrganizationUnit = column_ifexists('organization_unit', ''),
        OrignalFilePath = column_ifexists('orignal_file_path', ''),
        Os = column_ifexists('os', ''),
        OsVersion = column_ifexists('os_version', ''),
        OtherCategories = column_ifexists('other_categories', ''),
        OuterDocType = column_ifexists('outer_doc_type', ''),
        Owner = column_ifexists('owner', ''),
        Page = column_ifexists('page', ''),
        PageSite = column_ifexists('page_site', ''),
        ParentId = column_ifexists('parent_id', ''),
        Policy = column_ifexists('policy', ''),
        PolicyId = column_ifexists('policy_id', ''),
        Protocol = column_ifexists('protocol', ''),
        Referer = column_ifexists('referer', ''),
        ReqCnt = column_ifexists('req_cnt', ''),
        RequestId = column_ifexists('requestid', ''),
        RespCnt = column_ifexists('resp_cnt', ''),
        SAMAccountName = column_ifexists('sAMAccountName', ''),
        SanctionedInstance = column_ifexists('sanctioned_instance', ''),
        ScanType = column_ifexists('scan_type', ''),
        Serial = column_ifexists('serial', ''),
        ServerBytes = column_ifexists('server_bytes', ''),
        SessionId = column_ifexists('sessionid', ''),
        Severity = column_ifexists('severity', ''),
        Sfwder = column_ifexists('sfwder', ''),
        Sha256 = column_ifexists('sha256', ''),
        SharedWith = column_ifexists('shared_with', ''),
        Site = column_ifexists('site', ''),
        SmtpTo = column_ifexists('smtp_to', ''),
        SrcCountry = column_ifexists('src_country', ''),
        SrcGeoipSrc = column_ifexists('src_geoip_src', ''),
        SrcLatitude = column_ifexists('src_latitude', ''),
        SrcLocation = column_ifexists('src_location', ''),
        SrcLongitude = column_ifexists('src_longitude', ''),
        SrcRegion = column_ifexists('src_region', ''),
        SrcTime = column_ifexists('src_time', ''),
        SrcTimezone = column_ifexists('src_timezone', ''),
        SrcZipcode = column_ifexists('src_zipcode', ''),
        SrcIp = column_ifexists('srcip', ''),
        SuppressionEndTime = column_ifexists('suppression_end_time', ''),
        SuppressionKey = column_ifexists('suppression_key', ''),
        SuppressionStartTime = column_ifexists('suppression_start_time', ''),
        TelemetryApp = column_ifexists('telemetry_app', ''),
        Timestamp = column_ifexists('timestamp', ''),
        Title = column_ifexists('title_s', ''),
        ToUser = column_ifexists('to_user', ''),
        TotalCollaboratorCount = column_ifexists('total_collaborator_count', ''),
        TrafficType = column_ifexists('traffic_type', ''),
        TransactionId = column_ifexists('transactionid', ''),
        TrueObjCategory = column_ifexists('true_obj_category', ''),
        TrueObjType = column_ifexists('true_obj_type', ''),
        TssMode = column_ifexists('tss_mode', ''),
        PolicyType = column_ifexists('type_s', ''),
        UniversalConnector = column_ifexists('universal_connector', ''),
        UrNormalized = column_ifexists('ur_normalized', ''),
        Url = column_ifexists('url', ''),
        User = column_ifexists('user', ''),
        UserCategory = column_ifexists('user_category', ''),
        UserId = column_ifexists('user_id', ''),
        UserAgent = column_ifexists('useragent', ''),
        UserIp = column_ifexists('userip', ''),
        UserKey = column_ifexists('userkey', ''),
        UserPrincipalName = column_ifexists('userPrincipalName', ''),
        WebUniversalConnector = column_ifexists('web_universal_connector', ''),
        Workspace = column_ifexists('workspace', ''),
        WorkspaceId = column_ifexists('workspace_id', '')
    | project 
        TimeGenerated,
        AccessMethod,
        Action,
        Activity,
        Alert,
        AlertType,
        App,
        AppActivity,
        AppSessionId,
        AppCategory,
        AppSuite,
        AuditCategory,
        AuditType,
        Browser,
        BrowserSessionId,
        BrowserVersion,
        Category,
        Cci,
        Ccl,
        ChannelId,
        ClientBytes,
        ConnDuration,
        ConnectionId,
        CononicalName,
        CountI,
        CustomConnector,
        DataCenter,
        DataType,
        Device,
        DeviceClassification,
        DlpFile,
        DlpIncidentId,
        DlpIsUniqueCount,
        DlpMailParentId,
        DlpParentId,
        DlpProfile,
        DlpRule,
        DlpRuleCount,
        DlpRuleSeverity,
        DlpUniqueCount,
        DstCountry,
        DstGeoipSrc,
        DstLatitude,
        DstLocation,
        DstLongitude,
        DstRegion,
        DstTimezone,
        DstZipcode,
        DstHost,
        DstIp,
        DstPort,
        Exposure,
        FileLang,
        FilePath,
        FileSize,
        FileType,
        FromUser,
        FromUserCategory,
        FromLogs,
        HostName,
        Instance,
        InstanceId,
        InternalCollaboratorCount,
        LogFileName,
        LoginType,
        LoginUrl,
        ManagedApp,
        ManagementId,
        Md5,
        MimeType,
        Modified,
        NetskopeActivity,
        NetskopePop,
        NotifyTemplate,
        NsDeviceUid,
        NumBytes,
        Object,
        ObjectId,
        ObjectType,
        Org,
        OrganizationUnit,
        OrignalFilePath,
        Os,
        OsVersion,
        OtherCategories,
        OuterDocType,
        Owner,
        Page,
        PageSite,
        ParentId,
        Policy,
        PolicyId,
        Protocol,
        Referer,
        ReqCnt,
        RequestId,
        RespCnt,
        SAMAccountName,
        SanctionedInstance,
        ScanType,
        Serial,
        ServerBytes,
        SessionId,
        Severity,
        Sfwder,
        Sha256,
        SharedWith,
        Site,
        SmtpTo,
        SrcCountry,
        SrcGeoipSrc,
        SrcLatitude,
        SrcLocation,
        SrcLongitude,
        SrcRegion,
        SrcTime,
        SrcTimezone,
        SrcZipcode,
        SrcIp,
        SuppressionEndTime,
        SuppressionKey,
        SuppressionStartTime,
        TelemetryApp,
        Timestamp,
        Title,
        ToUser,
        TotalCollaboratorCount,
        TrafficType,
        TransactionId,
        TrueObjCategory,
        TrueObjType,
        TssMode,
        PolicyType,
        UniversalConnector,
        UrNormalized,
        Url,
        User,
        UserCategory,
        UserId,
        UserAgent,
        UserIp,
        UserKey,
        UserPrincipalName,
        WebUniversalConnector,
        Workspace,
        WorkspaceId
  };
  NetskopeEventsApplication