id: 3d3330e9-d11b-4b68-8861-251253950bd2
name: Cisco SE - Vulnerable applications
description: |
  'Query searches for vulnerable applications on hosts.'
severity: Medium
requiredDataConnectors:
  - connectorId: CiscoSecureEndpoint
    dataTypes:
      - CiscoSecureEndpoint
tactics:
  - Execution
relevantTechniques:
  - T1204.002
query: |
  CiscoSecureEndpoint
  | where TimeGenerated > ago(24h)
  | where EventMessage =~ 'Vulnerable Application Detected'
  | summarize by DstHostname
  | extend HostCustomEntity = DstHostname
entityMappings:
  - entityType: Host
    fieldMappings:
      - identifier: HostName
        columnName: HostCustomEntity
