name: 'validate-detections'
description: 'Validate Microsoft Sentinel Analytics Rules. Supported file types for detection rules are ARM templates (json) and yml files'
branding:
  icon: 'check-square'
  color: 'green'
inputs:
  filesPath:
    description:  'The path containing the detection rules.'
    required: false
    default: '.'
  logLevel:
    description:  'Verbosity level of the test results (see documentation).'
    required: false
    default: 'Normal'

runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/action.ps1 -FilesPath ${{ inputs.filesPath }} -LogLevel ${{ inputs.logLevel }}
      shell: pwsh
