id: 18833d01-703a-438d-8ac6-84faa82e9b52
name: Configuration Backup Job Failed
description: Detects failed configuration backup operations. This might indicate
  system or storage issues, or a potential sabotage of the backup infrastructure.
severity: Medium
status: Available
requiredDataConnectors:
- connectorId: Syslog
  dataTypes:
  - Syslog
- connectorId: SyslogAma
  dataTypes:
  - Syslog
queryFrequency: 3h
queryPeriod: 3h
triggerOperator: gt
triggerThreshold: 0
eventGroupingSettings:
  aggregationKind: AlertPerResult
tactics: []
relevantTechniques: []
query: "Veeam_GetFinishedConfigurationBackupSessions\r\n| where Result == \"Failed\"\
  \r\n| project\r\n    Date = format_datetime(TimeGenerated, 'dd.MM.yyyy HH:mm'),\r\
  \n    DataSource = Computer,\r\n    EventId = instanceId,\r\n    UserName = user,\r\
  \n    [\"State\"] = Result,\r\n     MessageDetails = Description"
version: 1.0.1
kind: Scheduled
customDetails:
  Date: Date
  DataSource: DataSource
  EventId: EventId
  MessageDetails: MessageDetails
