id: 215e89ca-cdbc-4661-b8b2-7041f6ecc7fb
name: Samsung Knox - Application Privilege Escalation or Change Events
version: 1.0.2
kind: NRT
description: When a Knox mobile app has transitioned from an acceptable uid/esuid/fsuid to a different, non-App id.
severity: High
status: Available
requiredDataConnectors:
  - connectorId: SamsungDCDefinition
    dataTypes:
      - Samsung_Knox_Process_CL
tactics:
  - PrivilegeEscalation
relevantTechniques:
  - T1548
query: |
  Samsung_Knox_Process_CL 
  | where Name == "PROCESS_PRIVILEGE_ESCALATION"
  | where MitreTtp has "T1548"
suppressionEnabled: false
suppressionDuration: PT5H
incidentConfiguration:
  createIncident: true
  groupingConfiguration:
    enabled: false
    reopenClosedIncident: false
    lookbackDuration: PT5H
    matchingMethod: AllEntities
eventGroupingSettings:
  aggregationKind: SingleAlert
