# trigger times in minutes
GET_AUDIT_EVENTS_TRIGGER_TIME = 5
GET_DLP_LOGS_TRIGGER_TIME = 5
GET_THREAT_INTEL_FEED_TRIGGER_TIME = 5
GET_TTP_ATTACHMENT_TRIGGER_TIME = 5
GET_TTP_IMPERSONATION_TRIGGER_TIME = 5
GET_TTP_URL_TRIGGER_TIME = 5
