id: 0b85a077-8ba5-4cb5-90f7-1e882afe10c5
name: GitHub - Oauth application - a client secret was removed
description: Detect activities when a client secret was removed. This query runs every day and its severity is Medium. queryFrequency=1d, queryPeriod=7d.
severity: Medium
status: Available
requiredDataConnectors:
- connectorId: GitHub
  dataTypes:
  - GitHubAuditData
queryFrequency: 1d
queryPeriod: 7d
triggerOperator: gt
triggerThreshold: 0
tactics:
- InitialAccess
relevantTechniques:
- T1078
- T1078.004
query: |
  GitHubAuditData
  | where Action == "oauth_application.remove_client_secret"
  | extend AccountName = tostring(split(Actor, "@")[0]), AccountUPNSuffix = tostring(split(Actor, "@")[1])
  | project TimeGenerated, Action, Actor, AccountName, AccountUPNSuffix
entityMappings:
- entityType: Account
  fieldMappings:
  - identifier: FullName
    columnName: Actor
  - identifier: Name
    columnName: AccountName
  - identifier: UPNSuffix
    columnName: AccountUPNSuffix
alertDetailsOverride:
  alertDisplayNameFormat: 'GitHub: client secret removed by {{Actor}}'
  alertDescriptionFormat: Action '{{Action}}' performed by {{Actor}} at {{TimeGenerated}}
customDetails:
  Action: Action
  TimeGenerated: TimeGenerated
eventGroupingSettings:
  aggregationKind: AlertPerResult
version: 1.0.2
kind: Scheduled