//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureSentinel_ManagementAPI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AzureSentinel_ManagementAPI.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please input action id: .
        /// </summary>
        internal static string Action_Id_Prompt_Text {
            get {
                return ResourceManager.GetString("Action_Id_Prompt_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please input existing action rule id:.
        /// </summary>
        internal static string Action_Rule_Id_Prompt_Text {
            get {
                return ResourceManager.GetString("Action_Rule_Id_Prompt_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions:.
        /// </summary>
        internal static string Actions_Menu {
            get {
                return ResourceManager.GetString("Actions_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert rule templates:.
        /// </summary>
        internal static string Alert_Rule_Template_Menu {
            get {
                return ResourceManager.GetString("Alert_Rule_Template_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert rules:.
        /// </summary>
        internal static string Alert_Rules_Menu {
            get {
                return ResourceManager.GetString("Alert_Rules_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 27.- BatchUpdateIncidents.
        /// </summary>
        internal static string Batch_Update_Incidents_Menu {
            get {
                return ResourceManager.GetString("Batch_Update_Incidents_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input existing bookmark id:.
        /// </summary>
        internal static string Bookmark_Prompt_Text {
            get {
                return ResourceManager.GetString("Bookmark_Prompt_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarks:.
        /// </summary>
        internal static string Bookmarks_Menu {
            get {
                return ResourceManager.GetString("Bookmarks_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please input comment id:.
        /// </summary>
        internal static string Comment_Id_Prompt_Text {
            get {
                return ResourceManager.GetString("Comment_Id_Prompt_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter to continue.
        /// </summary>
        internal static string Continue_Prompt_Text {
            get {
                return ResourceManager.GetString("Continue_Prompt_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.- CreateActionOfAlertRule - Attach a playbook to an analytic rule.
        /// </summary>
        internal static string Create_Action_Menu {
            get {
                return ResourceManager.GetString("Create_Action_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.- CreateBookmark.
        /// </summary>
        internal static string Create_Bookmark_Menu {
            get {
                return ResourceManager.GetString("Create_Bookmark_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21.- CreateDataConnector.
        /// </summary>
        internal static string Create_DataConnector_Menu {
            get {
                return ResourceManager.GetString("Create_DataConnector_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.- CreateFusionAlertRule.
        /// </summary>
        internal static string Create_Fusion_Rule_Menu {
            get {
                return ResourceManager.GetString("Create_Fusion_Rule_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28.- CreateIncidentComment.
        /// </summary>
        internal static string Create_Incident_Comment_Menu {
            get {
                return ResourceManager.GetString("Create_Incident_Comment_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22.- CreateIncident.
        /// </summary>
        internal static string Create_Incident_Menu {
            get {
                return ResourceManager.GetString("Create_Incident_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.- CreateMicrosoftSecurityIncidentCreationAlertRule.
        /// </summary>
        internal static string Create_Incident_Rule_Menu {
            get {
                return ResourceManager.GetString("Create_Incident_Rule_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31.- CreateIncidentRelation.
        /// </summary>
        internal static string Create_Relation_Menu {
            get {
                return ResourceManager.GetString("Create_Relation_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 36.- CreateSavedSearch.
        /// </summary>
        internal static string Create_Saved_Search_Menu {
            get {
                return ResourceManager.GetString("Create_Saved_Search_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.- CreateScheduledAlertRule.
        /// </summary>
        internal static string Create_Scheduled_Rule_Menu {
            get {
                return ResourceManager.GetString("Create_Scheduled_Rule_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please input data connector id:.
        /// </summary>
        internal static string Dataconnector_Prompt_Text {
            get {
                return ResourceManager.GetString("Dataconnector_Prompt_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataConnectors:.
        /// </summary>
        internal static string DataConnectors_Menu {
            get {
                return ResourceManager.GetString("DataConnectors_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.- DeleteActionOfAlertRule2.
        /// </summary>
        internal static string Delete_Action_Menu {
            get {
                return ResourceManager.GetString("Delete_Action_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.- DeleteBookmark.
        /// </summary>
        internal static string Delete_Bookmark_Menu {
            get {
                return ResourceManager.GetString("Delete_Bookmark_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.- DeleteDataConnector.
        /// </summary>
        internal static string Delete_DataConnector_Menu {
            get {
                return ResourceManager.GetString("Delete_DataConnector_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23.- DeleteIncident.
        /// </summary>
        internal static string Delete_Incident_Menu {
            get {
                return ResourceManager.GetString("Delete_Incident_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please input incident id (the incident&apos;s &apos;name&apos; field, aka Internal Incident Id) you want to delete:.
        /// </summary>
        internal static string Delete_Incident_Prompt_Text {
            get {
                return ResourceManager.GetString("Delete_Incident_Prompt_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32.- DeleteIncidentRelation.
        /// </summary>
        internal static string Delete_Relation_Menu {
            get {
                return ResourceManager.GetString("Delete_Relation_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.- DeleteAlertRule.
        /// </summary>
        internal static string Delete_Rule_Menu {
            get {
                return ResourceManager.GetString("Delete_Rule_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 37.- DeleteSavedSearch.
        /// </summary>
        internal static string Delete_Saved_Search_Menu {
            get {
                return ResourceManager.GetString("Delete_Saved_Search_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + C to exit.
        /// </summary>
        internal static string Exit_Text {
            get {
                return ResourceManager.GetString("Exit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.- GetActionOfAlertRuleById.
        /// </summary>
        internal static string Get_Action_By_Id_Menu {
            get {
                return ResourceManager.GetString("Get_Action_By_Id_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.- GetAllActionsByAlertRule.
        /// </summary>
        internal static string Get_Actions_Menu {
            get {
                return ResourceManager.GetString("Get_Actions_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17.- GetBookmarkById.
        /// </summary>
        internal static string Get_Bookmark_By_Id_Menu {
            get {
                return ResourceManager.GetString("Get_Bookmark_By_Id_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18.- GetBookmarks.
        /// </summary>
        internal static string Get_Bookmarks_Menu {
            get {
                return ResourceManager.GetString("Get_Bookmarks_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19.- GetDataConnectors.
        /// </summary>
        internal static string Get_DataConnectors_Menu {
            get {
                return ResourceManager.GetString("Get_DataConnectors_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 35.- GetIncidentEntitiesbyEntityType.
        /// </summary>
        internal static string Get_Entities_By_Type_Menu {
            get {
                return ResourceManager.GetString("Get_Entities_By_Type_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.- GetFusionAlertRule.
        /// </summary>
        internal static string Get_Fusion_Rule_Menu {
            get {
                return ResourceManager.GetString("Get_Fusion_Rule_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please input fusion alert rule id:.
        /// </summary>
        internal static string Get_Fusion_Rule_Prompt_Text {
            get {
                return ResourceManager.GetString("Get_Fusion_Rule_Prompt_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24.- GetIncidentByInternalId.
        /// </summary>
        internal static string Get_Incident_By_Id_Menu {
            get {
                return ResourceManager.GetString("Get_Incident_By_Id_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.- GetIncidentCommentById.
        /// </summary>
        internal static string Get_Incident_Comment_Menu {
            get {
                return ResourceManager.GetString("Get_Incident_Comment_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 29.- GetAllIncidentComments.
        /// </summary>
        internal static string Get_Incident_Comments_Menu {
            get {
                return ResourceManager.GetString("Get_Incident_Comments_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please input incident id (the incident&apos;s &apos;name&apos; field, aka Internal Incident Id) you want to get:.
        /// </summary>
        internal static string Get_Incident_Prompt_Text {
            get {
                return ResourceManager.GetString("Get_Incident_Prompt_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.- GetMicrosoftSecurityIncidentCreationAlertRule.
        /// </summary>
        internal static string Get_Incident_Rule_Menu {
            get {
                return ResourceManager.GetString("Get_Incident_Rule_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please input microsoft security incident alert rule id:.
        /// </summary>
        internal static string Get_Incident_Rule_Prompt_Text {
            get {
                return ResourceManager.GetString("Get_Incident_Rule_Prompt_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25.- GetIncidents.
        /// </summary>
        internal static string Get_Incidents_Menu {
            get {
                return ResourceManager.GetString("Get_Incidents_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 34.- GetIncidentRelationByName.
        /// </summary>
        internal static string Get_Relation_Menu {
            get {
                return ResourceManager.GetString("Get_Relation_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 33.- GetAllIncidentRelationsAndEntities.
        /// </summary>
        internal static string Get_Relations_Menu {
            get {
                return ResourceManager.GetString("Get_Relations_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.- GetAlertRuleTemplateById.
        /// </summary>
        internal static string Get_Rule_Template_By_Id_Menu {
            get {
                return ResourceManager.GetString("Get_Rule_Template_By_Id_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.- GetAlertRuleTemplates.
        /// </summary>
        internal static string Get_Rule_Templates_Menu {
            get {
                return ResourceManager.GetString("Get_Rule_Templates_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.- GetAllAlertRules.
        /// </summary>
        internal static string Get_Rules_Menu {
            get {
                return ResourceManager.GetString("Get_Rules_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 38.- GetSavedSearchById.
        /// </summary>
        internal static string Get_Saved_Search_Menu {
            get {
                return ResourceManager.GetString("Get_Saved_Search_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 39.- GetSavedSearches.
        /// </summary>
        internal static string Get_Saved_Searches_Menu {
            get {
                return ResourceManager.GetString("Get_Saved_Searches_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.- GetScheduledAlertRule.
        /// </summary>
        internal static string Get_Scheduled_Rule_Menu {
            get {
                return ResourceManager.GetString("Get_Scheduled_Rule_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please input scheduled alert rule id:.
        /// </summary>
        internal static string Get_Scheduled_Rule_Prompt_Text {
            get {
                return ResourceManager.GetString("Get_Scheduled_Rule_Prompt_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident comments:.
        /// </summary>
        internal static string Incident_Comments_Menu {
            get {
                return ResourceManager.GetString("Incident_Comments_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please input existing incident id ((the incident&apos;s &apos;name&apos; field, aka Internal Incident Id):.
        /// </summary>
        internal static string Incident_Id_Prompt_Text {
            get {
                return ResourceManager.GetString("Incident_Id_Prompt_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incidents:.
        /// </summary>
        internal static string Incident_Menu {
            get {
                return ResourceManager.GetString("Incident_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident relations:.
        /// </summary>
        internal static string Incident_Relation_Menu {
            get {
                return ResourceManager.GetString("Incident_Relation_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid option... please, press enter to continue....
        /// </summary>
        internal static string Invalid_Option_Text {
            get {
                return ResourceManager.GetString("Invalid_Option_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option:.
        /// </summary>
        internal static string Option {
            get {
                return ResourceManager.GetString("Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to related entities:.
        /// </summary>
        internal static string Related_Entities {
            get {
                return ResourceManager.GetString("Related_Entities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please input existing incident relation id:.
        /// </summary>
        internal static string Relation_Id_Prompt_Text {
            get {
                return ResourceManager.GetString("Relation_Id_Prompt_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please input alert rule id: .
        /// </summary>
        internal static string Rule_Id_Prompt_Text {
            get {
                return ResourceManager.GetString("Rule_Id_Prompt_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please input alert rule template id(Default is 157c0cfc-d76d-463b-8755-c781608cdc1a):.
        /// </summary>
        internal static string Rule_Template_Id_Prompt_Text {
            get {
                return ResourceManager.GetString("Rule_Template_Id_Prompt_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please input saved search id:.
        /// </summary>
        internal static string Saved_Search_Id_Prompt_Text {
            get {
                return ResourceManager.GetString("Saved_Search_Id_Prompt_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SavedSearches/Hunting queries:.
        /// </summary>
        internal static string Saved_Searches_Menu {
            get {
                return ResourceManager.GetString("Saved_Searches_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please an entity kind:.
        /// </summary>
        internal static string Select_Entity_Kind {
            get {
                return ResourceManager.GetString("Select_Entity_Kind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 26.- UpdateIncident.
        /// </summary>
        internal static string Update_Incident_Menu {
            get {
                return ResourceManager.GetString("Update_Incident_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40.- UpdateSavedSearch.
        /// </summary>
        internal static string Update_Saved_Search_Menu {
            get {
                return ResourceManager.GetString("Update_Saved_Search_Menu", resourceCulture);
            }
        }
    }
}
