"""
Generate an interactive ASIM Schema Browser HTML page.

Reads asim_fields.csv and asim_parsers.csv to produce a single-page HTML
application with primary tabs for each ASIM schema, and sub-tabs within each
schema for Fields (interactive DataTable) and Parsers.

The visual style matches index.html generated by generate_interactive_docs.py.
Links to entity pages (parser pages, solution pages, etc.) point to the
documentation generated by generate_interactive_docs.py/generate_connector_docs.py.

Output:
    asim-browser.html   - Single self-contained HTML page (CSS/JS inline)
"""

import argparse
import csv
import html as html_module
import re
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, Tuple
from urllib.parse import quote


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

DATATABLES_CSS = "https://cdn.datatables.net/1.13.8/css/dataTables.bootstrap5.min.css"
DATATABLES_JS = "https://cdn.datatables.net/1.13.8/js/jquery.dataTables.min.js"
DATATABLES_BS5_JS = "https://cdn.datatables.net/1.13.8/js/dataTables.bootstrap5.min.js"
JQUERY_JS = "https://code.jquery.com/jquery-3.7.1.min.js"

# Schemas excluded from browser tabs (supporting definitions, not standalone schemas)
SCHEMA_EXCLUDE = {'Common'}

# Field columns to display in the interactive table
FIELD_DISPLAY_COLUMNS = [
    ('field_name', 'Field'),
    ('field_class', 'Class'),
    ('physical_type', 'Type'),
    ('logical_type', 'Logical Type'),
    ('entity', 'Entity'),
    ('role', 'Role'),
    ('refers_to', 'Refers To'),
    ('description', 'Description'),
    ('source', 'Source'),
]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def esc(text: str) -> str:
    """HTML-escape a string."""
    return html_module.escape(str(text)) if text else ""


def sanitize_filename(text: str) -> str:
    """Convert text to safe filename, matching generate_connector_docs.py logic."""
    result = text.lower().replace(" ", "-").replace("/", "-").replace("_", "-")
    result = result.replace(":", "-").replace("*", "-").replace("?", "-")
    result = result.replace('"', "-").replace("<", "-").replace(">", "-").replace("|", "-")
    result = result.replace("(", "-").replace(")", "-").replace("%", "-")
    while "--" in result:
        result = result.replace("--", "-")
    result = result.strip("-")
    return result


def load_csv(path: Path) -> List[Dict[str, str]]:
    """Load a CSV file into a list of dicts."""
    rows = []
    if not path.exists():
        print(f"  Warning: {path} not found, skipping.")
        return rows
    with open(path, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append(row)
    return rows


# ---------------------------------------------------------------------------
# Data Loading
# ---------------------------------------------------------------------------

def load_fields_by_schema(fields_csv: Path) -> Dict[str, List[Dict[str, str]]]:
    """Load asim_fields.csv, group by schema.

    Returns dict: schema_name -> list of field dicts.
    Also includes 'Common' fields which will be merged into each schema tab.
    """
    by_schema: Dict[str, List[Dict[str, str]]] = defaultdict(list)
    for row in load_csv(fields_csv):
        schema = row.get('schema', '')
        if schema:
            by_schema[schema].append(row)
    return dict(by_schema)


def load_parsers_by_schema(parsers_csv: Path) -> Dict[str, List[Dict[str, str]]]:
    """Load asim_parsers.csv, group by schema.

    Returns dict: schema_name -> list of parser dicts, sorted by type then name.
    """
    by_schema: Dict[str, List[Dict[str, str]]] = defaultdict(list)
    for row in load_csv(parsers_csv):
        schema = row.get('schema', '')
        if schema and row.get('parser_type') != 'union':
            by_schema[schema].append(row)
    # Sort each schema's parsers alphabetically
    for schema in by_schema:
        by_schema[schema].sort(
            key=lambda p: p.get('parser_name', '').lower()
        )
    return dict(by_schema)


def load_logical_type_tooltips(logical_types_csv: Path) -> Dict[str, str]:
    """Load asim_logical_types.csv and build a name → tooltip description map.

    Strips markdown link syntax and HTML tags from descriptions to produce
    plain-text suitable for HTML title attributes.
    """
    tooltips: Dict[str, str] = {}
    for row in load_csv(logical_types_csv):
        name = row.get('name', '').strip()
        desc = row.get('description', '').strip()
        if not name:
            continue
        if not desc:
            tooltips[name] = ''
            continue
        # Strip markdown links [text](url) → text
        desc = re.sub(r'\[([^\]]+)\]\([^)]+\)', r'\1', desc)
        # Strip HTML tags (<br>, <br/>, etc.)
        desc = re.sub(r'<br\s*/?>', ' ', desc)
        desc = re.sub(r'<[^>]+>', '', desc)
        # Collapse whitespace
        desc = re.sub(r'\s+', ' ', desc).strip()
        tooltips[name] = desc
    return tooltips


# ---------------------------------------------------------------------------
# HTML Generation
# ---------------------------------------------------------------------------

def _generate_css() -> str:
    """Return the inline CSS for the page."""
    return """\
:root {
    --ms-blue: #0078d4;
    --ms-dark: #1b1a19;
    --ms-gray: #605e5c;
    --ms-light: #f3f2f1;
    --ms-border: #e1dfdd;
}

body {
    font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
    background: #faf9f8;
    color: var(--ms-dark);
    margin: 0;
    padding: 0;
}

.navbar {
    background: var(--ms-blue) !important;
    padding: 8px 20px;
    display: flex;
    align-items: center;
    justify-content: space-between;
}
.navbar-brand {
    color: #fff;
    font-weight: 600;
    font-size: 1.1rem;
    text-decoration: none;
}
.navbar-brand:hover { color: #fff; }
.navbar-nav-links {
    display: flex;
    gap: 16px;
    align-items: center;
}
.nav-doc-link {
    color: rgba(255,255,255,0.85);
    text-decoration: none;
    font-size: 0.85rem;
}
.nav-doc-link:hover { color: #fff; }

.container-fluid {
    max-width: 1600px;
    margin: 0 auto;
    padding: 0 16px;
}

/* Schema tabs (primary) */
.schema-tabs .nav-link {
    color: var(--ms-gray);
    font-weight: 500;
    border: none;
    padding: 0.75rem 1.25rem;
}
.schema-tabs .nav-link.active {
    color: var(--ms-blue);
    border-bottom: 3px solid var(--ms-blue);
    background: transparent;
}
.schema-tabs .nav-link:hover:not(.active) {
    color: var(--ms-dark);
    border-bottom: 3px solid var(--ms-border);
}
.tab-badge {
    font-size: 0.75rem;
    padding: 0.2em 0.5em;
    vertical-align: middle;
    margin-left: 4px;
}

/* Sub-tabs */
.sub-tabs .nav-link {
    color: var(--ms-gray);
    font-size: 0.9rem;
    padding: 0.5rem 1rem;
    border: none;
}
.sub-tabs .nav-link.active {
    color: var(--ms-blue);
    border-bottom: 2px solid var(--ms-blue);
    background: transparent;
    font-weight: 500;
}
.sub-tabs .nav-link:hover:not(.active) {
    color: var(--ms-dark);
}

/* Summary cards */
.summary-card {
    background: white;
    border: 1px solid var(--ms-border);
    border-radius: 8px;
    padding: 1rem 1.25rem;
    text-align: center;
}
.summary-card .number {
    font-size: 2rem;
    font-weight: 700;
    color: var(--ms-blue);
    line-height: 1.2;
}
.summary-card .label {
    font-size: 0.85rem;
    color: var(--ms-gray);
}

/* DataTable overrides */
.dataTables_wrapper { padding-top: 0.5rem; }
table.dataTable { font-size: 0.875rem; }
table.dataTable thead th {
    background: var(--ms-light);
    border-bottom: 2px solid var(--ms-border);
    font-weight: 600;
    font-size: 0.8rem;
    text-transform: uppercase;
    letter-spacing: 0.03em;
    white-space: nowrap;
}
table.dataTable thead tr.filters th {
    background: white;
    border-bottom: 1px solid var(--ms-border);
    padding: 4px 6px;
    font-weight: normal;
    text-transform: none;
}
table.dataTable tbody td {
    vertical-align: middle;
    padding: 0.5rem 0.75rem;
}
table.dataTable tbody tr:hover {
    background: #e8f4fd !important;
}
table.dataTable tbody td {
    cursor: pointer;
}
table.dataTable a {
    color: var(--ms-blue);
    text-decoration: none;
}
table.dataTable a:hover {
    text-decoration: underline;
}

/* Column filter inputs */
.column-filter {
    width: 100%;
    padding: 2px 6px;
    font-size: 0.78rem;
    border: 1px solid var(--ms-border);
    border-radius: 3px;
    margin-top: 4px;
}
.column-filter:focus {
    outline: none;
    border-color: var(--ms-blue);
}

/* Clear filters bar */
.clear-filters-bar {
    display: none;
    padding: 5px 12px;
    margin-bottom: 4px;
    border-radius: 4px;
    background: #fff4ce;
    border: 1px solid #f0d060;
    font-size: 0.82rem;
    color: #6b5900;
    align-items: center;
    justify-content: space-between;
}
.clear-filters-bar.visible { display: flex; }
.clear-filters-bar .clear-label { font-weight: 500; }
.clear-filters-bar .btn-clear-all {
    font-size: 0.78rem;
    padding: 2px 12px;
    border: 1px solid #d4a800;
    border-radius: 4px;
    background: #fff;
    color: #6b5900;
    cursor: pointer;
    font-weight: 500;
}
.clear-filters-bar .btn-clear-all:hover {
    background: #ffeea0;
    border-color: #b08f00;
}

/* Status badges */
.badge-active { background: #107c10; }
.badge-deprecated { background: #a80000; }
.badge-unpublished { background: #ca5010; }
.badge-discovered { background: #8764b8; }

/* Class badges for fields */
.class-mandatory { color: #a80000; font-weight: 600; }
.class-recommended { color: #ca5010; font-weight: 600; }
.class-optional { color: var(--ms-gray); }
.class-conditional { color: #8764b8; font-weight: 500; }
.class-alias { color: #0078d4; font-style: italic; }

/* Tooltip hint styling */
.has-tooltip { border-bottom: 1px dotted currentColor; cursor: help; }
th.has-tooltip { border-bottom: 2px dotted var(--ms-gray); cursor: help; }

/* Source badges */
.source-testeronly { color: #ca5010; cursor: help; }
.source-physicalonly { color: #8764b8; cursor: help; }

/* Legend */
.table-legend {
    margin-top: 0.5rem;
    padding: 0.4rem 0.8rem;
    font-size: 0.78rem;
    color: var(--ms-gray);
    display: flex;
    flex-wrap: wrap;
    gap: 1rem;
}
.table-legend .legend-item {
    display: inline-flex;
    align-items: center;
    gap: 0.3rem;
}

/* Description column */
td.col-desc {
    max-width: 650px;
    white-space: normal;
    word-wrap: break-word;
}
td.col-desc .desc-example {
    color: var(--ms-gray);
    font-size: 0.9em;
}
details.desc-values {
    margin-top: 4px;
    font-size: 0.9em;
    color: var(--ms-gray);
}
details.desc-values summary {
    cursor: pointer;
    color: var(--ms-blue);
    font-size: 0.85em;
}
details.desc-values summary:hover { text-decoration: underline; }

/* Loading overlay */
.loading-overlay {
    position: fixed;
    top: 0; left: 0; right: 0; bottom: 0;
    background: rgba(255,255,255,0.9);
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 9999;
    font-size: 1.2rem;
    color: var(--ms-blue);
}

/* Footer */
.footer {
    margin-top: 2rem;
    padding: 1rem 0;
    color: var(--ms-gray);
    font-size: 0.8rem;
    text-align: center;
    border-top: 1px solid var(--ms-border);
}

/* Bool indicators */
.bool-yes { color: #107c10; font-weight: 600; }
.bool-no { color: #ccc; }
"""


def _generate_js() -> str:
    """Return the inline JavaScript for the page."""
    return """\
$(document).ready(function() {
    // Common DataTable config
    var dtDefaults = {
        pageLength: 50,
        lengthMenu: [[25, 50, 100, -1], [25, 50, 100, "All"]],
        order: [],
        autoWidth: false,
        deferRender: true,
        stateSave: false,
        orderCellsTop: true,
        dom: '<"row"<"col-sm-6"li><"col-sm-6"f>>rtip',
        language: {
            search: "Quick filter:",
            lengthMenu: "Show _MENU_ rows",
            info: "Showing _START_-_END_ of _TOTAL_",
            emptyTable: "No matching records",
        }
    };

    // Track initialized tables to avoid double-init
    var initializedTables = {};

    function initTable(tableId, extraOpts) {
        if (initializedTables[tableId]) return initializedTables[tableId];
        var $table = $('#' + tableId);
        if (!$table.length) return null;

        var opts = $.extend(true, {}, dtDefaults, extraOpts || {});
        opts.initComplete = function() {
            var api = this.api();
            $('#' + tableId + ' thead tr.filters th').each(function(i) {
                var column = api.column(i);
                if ($(this).data('filter') !== false) {
                    $('<input type="text" class="column-filter" placeholder="Filter...">')
                        .appendTo($(this).empty())
                        .on('keyup change clear', function() {
                            if (column.search() !== this.value) {
                                column.search(this.value).draw();
                            }
                            updateClearBtn(tableId, api);
                        });
                }
            });

            var clearBar = $(
                '<div class="clear-filters-bar">' +
                '<span class="clear-label">Filters are active</span>' +
                '<button class="btn-clear-all" title="Clear all filters">✕ Clear All Filters</button>' +
                '</div>'
            );
            clearBar.find('.btn-clear-all').on('click', function() {
                api.search('');
                api.columns().every(function() { this.search(''); });
                $('#' + tableId + ' thead tr.filters input.column-filter').val('');
                $(api.table().container()).find('.dataTables_filter input').val('');
                api.draw();
                clearBar.removeClass('visible');
            });
            $(api.table().container()).prepend(clearBar);

            $(api.table().container()).find('.dataTables_filter input').on('keyup change clear', function() {
                updateClearBtn(tableId, api);
            });
            updateClearBtn(tableId, api);
        };
        var dt = $table.DataTable(opts);
        initializedTables[tableId] = dt;
        return dt;
    }

    function updateClearBtn(tableId, api) {
        var hasFilter = !!api.search();
        if (!hasFilter) {
            api.columns().every(function() { if (this.search()) hasFilter = true; });
        }
        $(api.table().container()).find('.clear-filters-bar').toggleClass('visible', hasFilter);
    }

    // Initialize tables when their sub-tab becomes visible
    function initVisibleTable(schemaId) {
        var fieldsTableId = schemaId + '-fields-table';
        var parsersTableId = schemaId + '-parsers-table';

        if ($('#' + fieldsTableId).length && !initializedTables[fieldsTableId]) {
            // Find description column index dynamically (it has col-desc class in tbody)
            var descIdx = -1;
            $('#' + fieldsTableId + ' thead tr:first th').each(function(i) {
                if ($(this).text().trim() === 'Description') descIdx = i;
            });
            var colDefs = [];
            if (descIdx >= 0) colDefs.push({ targets: descIdx, className: 'col-desc' });
            initTable(fieldsTableId, {
                order: [[0, 'asc']],
                columnDefs: colDefs,
            });
        }
        if ($('#' + parsersTableId).length && !initializedTables[parsersTableId]) {
            initTable(parsersTableId, {
                order: [[2, 'asc'], [0, 'asc']],
            });
        }
    }

    // Schema tab switching
    $('button[data-bs-toggle="tab"]').on('shown.bs.tab', function(e) {
        var targetId = $(e.target).data('bs-target');
        // If this is a schema tab, init its tables
        if (targetId) {
            var schemaId = targetId.replace('#', '').replace('-pane', '');
            initVisibleTable(schemaId);
        }
        // Adjust DataTable columns on any tab show
        $.fn.dataTable.tables({ visible: true, api: true }).columns.adjust();

        // Update URL hash
        var id = $(e.target).attr('id');
        if (id) {
            // Build hash from schema tab + sub-tab
            var hash = id.replace('-tab', '');
            history.replaceState(null, '', '#' + hash);
        }
    });

    // Activate tab from URL hash
    function activateFromHash() {
        var hash = window.location.hash.replace('#', '');
        if (!hash) return;
        // Try as schema tab
        var tabBtn = document.getElementById(hash + '-tab');
        if (tabBtn) {
            bootstrap.Tab.getOrCreateInstance(tabBtn).show();
        }
    }

    // Initialize default (first visible) schema tables
    var firstSchemaPane = $('.schema-pane.show');
    if (firstSchemaPane.length) {
        var schemaId = firstSchemaPane.attr('id').replace('-pane', '');
        initVisibleTable(schemaId);
    }

    activateFromHash();
    $(window).on('hashchange', activateFromHash);
    window.addEventListener('pageshow', function(e) {
        if (e.persisted) activateFromHash();
    });

    // Click-to-filter
    $(document).on('click', 'table.dataTable tbody td', function(e) {
        if ($(e.target).closest('a, details, summary').length) return;
        var table = $(this).closest('table').DataTable();
        var colIdx = table.cell(this).index().column;
        var text = $(this).text().trim();
        if (!text || text === '—') return;
        var th = $($(this).closest('table').find('thead tr.filters th')[colIdx]);
        if (th.data('filter') === false) return;
        var input = th.find('input.column-filter');
        if (input.length) {
            input.val(text).trigger('change');
        }
    });

    // Hide loading
    $('#loading').fadeOut(200);
});
"""


# Tooltip descriptions for field class values
_CLASS_TOOLTIPS = {
    'Mandatory': (
        'Mandatory fields must be populated by every ASIM parser. If the source '
        'does not provide data for a mandatory field, the parser should use a '
        'reasonable default or leave it empty, but the field column must always '
        'be present in the output. Mandatory fields are essential for '
        'cross-source correlation and detection rules to function correctly.'
    ),
    'Recommended': (
        'Recommended fields should be populated whenever the source data contains '
        'the relevant information. These fields significantly enrich the normalized '
        'event and improve the accuracy of analytics, hunting queries, and '
        'workbooks. Omitting them is acceptable when the source genuinely lacks '
        'the data, but parsers should make a best effort to map them.'
    ),
    'Optional': (
        'Optional fields may be populated if the source provides the data, but '
        'their absence is fully expected and will not affect detection rules or '
        'standard analytics. These fields provide additional context and detail '
        'for deeper investigations and are most useful for enrichment scenarios.'
    ),
    'Conditional': (
        'Conditional fields are required only when specific conditions are met, '
        'such as when a related field is populated or when the event is of a '
        'particular subtype. The schema documentation specifies the exact '
        'conditions under which each conditional field becomes mandatory. '
        'Parsers must include them when the condition applies.'
    ),
    'Alias': (
        'Alias fields are computed columns that provide an alternative name for '
        'another field, typically to support backward compatibility or to offer '
        'a shorter, more convenient name. Aliases are not stored independently '
        'but are derived at query time. For example, "User" may alias '
        '"TargetUsername" for convenience in interactive queries.'
    ),
}

# Tooltip descriptions for entity values
_ENTITY_TOOLTIPS = {
    'user': (
        'A user or identity entity representing a person, service account, or '
        'managed identity. User fields capture attributes such as username, '
        'user ID, UPN, Azure AD object ID, SID, and the type of identity. '
        'Depending on the role, a user entity may represent the actor performing '
        'an action, the target of an action, or an owner of a resource.'
    ),
    'device': (
        'A device entity representing a machine, host, or network endpoint. '
        'Device fields capture hostname, FQDN, IP address, MAC address, and '
        'operating system details. Devices can appear in multiple roles such as '
        'the source initiating traffic, the destination receiving it, or the '
        'reporting device (Dvc) that generated the log event.'
    ),
    'process': (
        'A process entity representing a running program or executable on a '
        'system. Process fields capture the process name, command line, process '
        'ID, file path, and hash values. Process entities appear in schemas like '
        'ProcessEvent and can have hierarchical relationships through the parent '
        'role, linking child processes to their creating parent process.'
    ),
    'application': (
        'An application entity representing a software application, cloud '
        'service, or logical component. Application fields capture the '
        'application name, ID, and type. Applications are commonly referenced '
        'in authentication events (the app being accessed), web sessions '
        '(the web application or URL), and audit events (the service being '
        'administered).'
    ),
}

# Tooltip descriptions for role values
_ROLE_TOOLTIPS = {
    'src': (
        'The source role identifies the originating endpoint of a network '
        'connection or activity. Source fields include IP address, hostname, port, '
        'geographic location, and associated user. In network sessions, the source '
        'is the client initiating the connection. In authentication events, it is '
        'the machine from which the logon attempt originates.'
    ),
    'dst': (
        'The destination role identifies the receiving endpoint of a network '
        'connection or activity. Destination fields include IP address, hostname, '
        'port, geographic location, and associated application or resource. In '
        'network sessions, the destination is the server accepting the connection. '
        'In DNS events, it is the DNS server processing the query.'
    ),
    'dvc': (
        'The Dvc (device) role identifies the reporting device that generated or '
        'forwarded the log event. This is the system whose logs are being parsed, '
        'which may differ from the source and destination. For example, a firewall '
        'reporting on traffic is the Dvc, while the client and server are the Src '
        'and Dst respectively. Dvc fields include hostname, IP, and OS details.'
    ),
    'actor': (
        'The actor role identifies the user or identity performing an action. '
        'Actor fields capture the username, user type, and identifiers of the '
        'person or service account initiating the event. In authentication events, '
        'the actor is the user logging in. In audit events, the actor is the '
        'administrator making a configuration change.'
    ),
    'acting': (
        'The acting role identifies the active entity executing an operation, '
        'similar to actor but used in schemas where the emphasis is on the '
        'process or application performing the action rather than the human user. '
        'For example, in process events, the acting process is the one creating '
        'a child process or modifying a file.'
    ),
    'target': (
        'The target role identifies the entity being acted upon. In user '
        'management events, the target is the user account being created, '
        'modified, or deleted. In authentication, the target may be the '
        'application or resource being accessed. Target fields capture the same '
        'attributes as other roles (username, hostname, etc.) but for the '
        'receiving entity of the action.'
    ),
    'parent': (
        'The parent role identifies the process that created or spawned the '
        'current process. Parent fields capture the parent process name, ID, '
        'command line, and file hash. This role enables building process trees '
        'for threat hunting and forensic analysis, linking a suspicious child '
        'process back through its ancestry to the initial execution.'
    ),
    'intermediary': (
        'The intermediary role identifies a device or service that sits between '
        'the source and destination, mediating or relaying the activity. Common '
        'examples include proxy servers, load balancers, and mail relays. '
        'Intermediary fields capture the hostname, IP address, and other '
        'attributes of these middle-tier devices that may modify, inspect, or '
        'forward the traffic.'
    ),
}

# Column header tooltips
_COLUMN_TOOLTIPS = {
    'field_class': (
        'The field class indicates how important this field is in the ASIM schema: '
        'Mandatory (must always be present), Recommended (should be present if '
        'data is available), Optional (nice to have), Conditional (required under '
        'specific conditions), or Alias (computed reference to another field).'
    ),
    'entity': (
        'The entity type describes what kind of object this field relates to: '
        'User (identity/account), Device (host/endpoint), Process (running '
        'program), or Application (software service). Fields with the same '
        'entity and role are grouped together logically in the schema.'
    ),
    'role': (
        'The role describes the function of the entity in the event context: '
        'Src (source/initiator), Dst (destination/target endpoint), Dvc '
        '(reporting device), Actor (user performing action), Target (entity '
        'being acted upon), Parent (parent process), or Intermediary (mediating '
        'device like a proxy).'
    ),
    'refers_to': (
        'For Alias fields, shows the field(s) this alias references. For '
        'Conditional fields, shows the field whose presence makes this field '
        'required. For example, DvcIdType is conditional on DvcId — it must '
        'be populated whenever DvcId is set.'
    ),
}


def _format_field_class(cls: str) -> str:
    """Format field class with color styling and tooltip."""
    css_class = {
        'Mandatory': 'class-mandatory',
        'Recommended': 'class-recommended',
        'Optional': 'class-optional',
        'Conditional': 'class-conditional',
        'Alias': 'class-alias',
    }.get(cls, '')
    tooltip = _CLASS_TOOLTIPS.get(cls, '')
    if css_class:
        title_attr = f' title="{esc(tooltip)}"' if tooltip else ''
        return f'<span class="{css_class} has-tooltip"{title_attr}>{esc(cls)}</span>'
    return esc(cls)


def _format_refers_to(field: dict) -> str:
    """Format the refers-to value for alias and conditional fields."""
    cls = field.get('field_class', '')
    if cls == 'Alias':
        raw = field.get('aliased_field', '').strip()
    elif cls == 'Conditional':
        raw = field.get('conditional_on', '').strip()
    else:
        return ''
    if not raw:
        return ''
    # Display pipe-separated values as comma-separated
    parts = [p.strip() for p in raw.split('|') if p.strip()]
    if len(parts) > 1 and cls == 'Alias':
        return 'Either of ' + esc(', '.join(parts))
    return esc(', '.join(parts))


def _format_entity(val: str) -> str:
    """Format entity value with tooltip."""
    if not val:
        return ''
    tooltip = _ENTITY_TOOLTIPS.get(val.lower(), '')
    display = esc(val.capitalize())
    if tooltip:
        return f'<span class="has-tooltip" title="{esc(tooltip)}">{display}</span>'
    return display


def _format_role(val: str) -> str:
    """Format role value with tooltip."""
    if not val:
        return ''
    tooltip = _ROLE_TOOLTIPS.get(val.lower(), '')
    display = esc(val.capitalize())
    if tooltip:
        return f'<span class="has-tooltip" title="{esc(tooltip)}">{display}</span>'
    return display


# Module-level logical type tooltips (populated by generate_asim_browser)
_LOGICAL_TYPE_TOOLTIPS: Dict[str, str] = {}


def _format_logical_type(val: str, allowed_values: str = '') -> str:
    """Format logical type value with tooltip and optional collapsible allowed values."""
    if not val and not allowed_values:
        return ''
    parts_out = []
    if val:
        tooltip = _LOGICAL_TYPE_TOOLTIPS.get(val, '')
        display = esc(val)
        if tooltip:
            parts_out.append(f'<span class="has-tooltip" title="{esc(tooltip)}">{display}</span>')
        else:
            parts_out.append(display)
    if allowed_values:
        vals = [v.strip() for v in allowed_values.split('|') if v.strip()]
        if vals:
            val_list = ', '.join(esc(v) for v in vals)
            parts_out.append(
                f'<details class="desc-values"><summary>Values ({len(vals)})</summary>'
                f'{val_list}</details>'
            )
    return ''.join(parts_out)


_SOURCE_INFO: Dict[str, tuple] = {
    # source_key: (display_name, tooltip)
    'SchemaDoc': ('Schema', 'Documented in the schema page on Microsoft Learn'),
    'CommonFields': ('Common', 'Documented in the ASIM common fields page on Microsoft Learn'),
    'CommonFieldsRef': ('Common', 'Documented in the ASIM common fields page on Microsoft Learn'),
    'CommonFieldsImplicit': ('Common (Implicit)', 'Standard Log Analytics column implicitly included in every ASIM schema'),
    'InheritedFromNetworkSession': ('Inherited', 'Inherited from the NetworkSession schema into WebSession'),
    'EntityExtension': ('Entity Extension', 'Inferred from ASIM entity definitions and role prefixes used in this schema'),
    'TesterOnly': ('Tester Only', 'Present in the ASIM tester but not in schema documentation'),
    'PhysicalTableOnly': ('Physical Table Only', 'Present in the physical Log Analytics table but not in schema documentation or the tester'),
}


def _format_source(source: str) -> str:
    """Format field source with highlighting and tooltip."""
    info = _SOURCE_INFO.get(source)
    if info:
        display, tooltip = info
        css = ''
        if source == 'TesterOnly':
            css = ' class="source-testeronly"'
        elif source == 'PhysicalTableOnly':
            css = ' class="source-physicalonly"'
        else:
            css = ' class="has-tooltip"'
        return f'<span{css} title="{esc(tooltip)}">{esc(display)}</span>'
    return esc(source)


def _format_description(desc: str, example: str = '') -> str:
    """Clean up description for display. Appends example if provided."""
    if not desc and not example:
        return ''
    parts = []
    if desc:
        # Strip HTML-like tags from original_description leakage
        desc = re.sub(r'<br\s*/?>', ' ', desc)
        desc = re.sub(r'<[^>]+>', '', desc)
        parts.append(esc(desc))
    if example:
        parts.append(f'<span class="desc-example"> (e.g. {esc(example)})</span>')
    return ''.join(parts)


def generate_asim_browser(
    fields_csv: Path,
    parsers_csv: Path,
    output_dir: Path,
    docs_base_path: str = '',
    index_url: str = '',
    link_extension: str = '.html',
) -> Path:
    """Generate the ASIM browser HTML page.

    Args:
        fields_csv: Path to asim_fields.csv.
        parsers_csv: Path to asim_parsers.csv.
        output_dir: Directory to write asim-browser.html into.
        docs_base_path: Relative path prefix from asim-browser.html to entity
            doc pages (e.g. "Solutions Docs/" when the page is at repo root).
        index_url: URL to the main index.html page for the navbar link.
        link_extension: File extension for entity page links (".html" or ".md").

    Returns:
        Path to the generated asim-browser.html.
    """
    print("Generating ASIM Schema Browser...")

    # Load data
    print("  Loading ASIM fields...")
    fields_by_schema = load_fields_by_schema(fields_csv)
    print("  Loading ASIM parsers...")
    parsers_by_schema = load_parsers_by_schema(parsers_csv)

    # Load logical type tooltips
    logical_types_csv = fields_csv.parent / 'asim_logical_types.csv'
    global _LOGICAL_TYPE_TOOLTIPS
    _LOGICAL_TYPE_TOOLTIPS = load_logical_type_tooltips(logical_types_csv)
    if _LOGICAL_TYPE_TOOLTIPS:
        print(f"  Loaded {len(_LOGICAL_TYPE_TOOLTIPS)} logical type descriptions")

    # Get common fields (to include in each schema)
    common_fields = fields_by_schema.get('Common', [])

    # Determine which schemas to show, grouped by type (event first, then entity).
    # Schema type is read from the CSV; schemas without a type default to 'event'.
    schema_types: Dict[str, str] = {}  # schema_name -> 'event' or 'entity'
    for schema_name, field_rows in fields_by_schema.items():
        if schema_name in SCHEMA_EXCLUDE:
            continue
        for row in field_rows:
            st = row.get('schema_type', '')
            if st:
                schema_types[schema_name] = st
                break
        else:
            schema_types[schema_name] = 'event'

    schemas = sorted(schema_types.keys(), key=str.casefold)

    # Compute counts
    total_fields = sum(len(fields_by_schema.get(s, [])) for s in schemas)
    total_parsers = sum(len(parsers_by_schema.get(s, [])) for s in schemas)

    print(f"  Schemas: {len(schemas)}, Fields: {total_fields}, Parsers: {total_parsers}")

    # Build HTML
    parts = []

    # ---- Head ----
    parts.append(f"""\
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ASIM Schema Browser &mdash; Microsoft Sentinel</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="{DATATABLES_CSS}" rel="stylesheet">
    <style>
{_generate_css()}
    </style>
</head>
<body>

<div id="loading" class="loading-overlay">Loading ASIM Schema Browser&hellip;</div>

<nav class="navbar">
    <a href="{'asim-browser.html'}" class="navbar-brand">Microsoft Sentinel &mdash; ASIM Schema Browser</a>
    <div class="navbar-nav-links">
""")

    if index_url:
        parts.append(f'        <a href="{esc(index_url)}" class="nav-doc-link" title="Solutions Analyzer Index">📊 Solutions Analyzer</a>\n')
    parts.append(f'        <a href="https://learn.microsoft.com/azure/sentinel/normalization" class="nav-doc-link" title="ASIM documentation on Microsoft Learn">📖 ASIM Docs</a>\n')
    if docs_base_path:
        parts.append(f'        <a href="{docs_base_path}asim/asim-products-index{link_extension}" class="nav-doc-link" title="ASIM Products">🏭 ASIM Products</a>\n')

    parts.append("""\
    </div>
</nav>

<div class="container-fluid py-3">
""")

    # ---- Summary cards ----
    parts.append(f"""\
<div class="row g-3 mb-3">
    <div class="col"><div class="summary-card"><div class="number">{len(schemas)}</div><div class="label">Schemas</div></div></div>
    <div class="col"><div class="summary-card"><div class="number">{total_fields}</div><div class="label">Schema Fields</div></div></div>
    <div class="col"><div class="summary-card"><div class="number">{len(common_fields)}</div><div class="label">Common Fields</div></div></div>
    <div class="col"><div class="summary-card"><div class="number">{total_parsers}</div><div class="label">Source Parsers</div></div></div>
</div>
""")

    # ---- Schema Tabs ----
    parts.append('<ul class="nav nav-tabs schema-tabs" id="schemaTabs" role="tablist">\n')
    for i, schema in enumerate(schemas):
        active = ' active' if i == 0 else ''
        field_count = len(fields_by_schema.get(schema, []))
        schema_id = sanitize_filename(schema)
        is_entity = schema_types.get(schema) == 'entity'
        badge_class = 'bg-info' if is_entity else 'bg-primary'
        parts.append(f"""\
    <li class="nav-item" role="presentation">
        <button class="nav-link{active}" id="{schema_id}-tab" data-bs-toggle="tab" data-bs-target="#{schema_id}-pane" type="button" role="tab"{' title="Entity Schema"' if is_entity else ''}>
            {esc(schema)} <span class="badge tab-badge {badge_class}">{field_count}</span>
        </button>
    </li>
""")
    parts.append('</ul>\n\n')

    # ---- Tab Panes ----
    parts.append('<div class="tab-content mt-2" id="schemaTabContent">\n')

    for i, schema in enumerate(schemas):
        active_class = ' show active' if i == 0 else ''
        schema_id = sanitize_filename(schema)
        schema_fields = fields_by_schema.get(schema, [])
        schema_parsers = parsers_by_schema.get(schema, [])

        parts.append(f'<div class="tab-pane fade{active_class} schema-pane" id="{schema_id}-pane" role="tabpanel">\n')

        # Sub-tabs
        parts.append(f"""\
<ul class="nav nav-tabs sub-tabs mt-2" id="sub-{schema_id}" role="tablist">
    <li class="nav-item" role="presentation">
        <button class="nav-link active" id="{schema_id}-fields-stab" data-bs-toggle="tab" data-bs-target="#{schema_id}-fields-pane" type="button" role="tab">
            Fields <span class="badge tab-badge bg-secondary">{len(schema_fields)}</span>
        </button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="{schema_id}-parsers-stab" data-bs-toggle="tab" data-bs-target="#{schema_id}-parsers-pane" type="button" role="tab">
            Parsers <span class="badge tab-badge bg-secondary">{len(schema_parsers)}</span>
        </button>
    </li>
</ul>
<div class="tab-content mt-2">
""")

        # ---- Fields Sub-tab ----
        parts.append(f'<div class="tab-pane fade show active" id="{schema_id}-fields-pane" role="tabpanel">\n')

        # Entity schemas don't need Entity/Role columns
        is_entity = schema_types.get(schema) == 'entity'
        display_columns = [(k, l) for k, l in FIELD_DISPLAY_COLUMNS
                           if not (is_entity and k in ('entity', 'role'))]

        # Fields table
        parts.append(f"""\
<table id="{schema_id}-fields-table" class="table table-striped table-hover" style="width:100%">
<thead>
<tr>
""")
        for col_key, col_label in display_columns:
            tooltip = _COLUMN_TOOLTIPS.get(col_key, '')
            if tooltip:
                parts.append(f'    <th class="has-tooltip" title="{esc(tooltip)}">{col_label}</th>\n')
            else:
                parts.append(f'    <th>{col_label}</th>\n')
        parts.append('</tr>\n<tr class="filters">\n')
        for col_key, col_label in display_columns:
            parts.append('    <th></th>\n')
        parts.append('</tr>\n</thead>\n<tbody>\n')

        for field in sorted(schema_fields, key=lambda f: f.get('field_name', '').lower()):
            parts.append('<tr>')
            for col_key, col_label in display_columns:
                val = field.get(col_key, '')
                if col_key == 'field_class':
                    parts.append(f'<td>{_format_field_class(val)}</td>')
                elif col_key == 'source':
                    parts.append(f'<td>{_format_source(val)}</td>')
                elif col_key == 'description':
                    example = field.get('example', '')
                    parts.append(f'<td class="col-desc">{_format_description(val, example)}</td>')
                elif col_key == 'refers_to':
                    parts.append(f'<td>{_format_refers_to(field)}</td>')
                elif col_key == 'entity':
                    parts.append(f'<td>{_format_entity(val)}</td>')
                elif col_key == 'role':
                    parts.append(f'<td>{_format_role(val)}</td>')
                elif col_key == 'logical_type':
                    allowed_values = field.get('allowed_values', '')
                    parts.append(f'<td>{_format_logical_type(val, allowed_values)}</td>')
                else:
                    parts.append(f'<td>{esc(val)}</td>')
            parts.append('</tr>\n')

        parts.append('</tbody></table>\n')
        parts.append("""\
<div class="table-legend">
    <span class="legend-item"><span class="class-mandatory">Mandatory</span> Must be present</span>
    <span class="legend-item"><span class="class-recommended">Recommended</span> Should be present</span>
    <span class="legend-item"><span class="class-optional">Optional</span> May be present</span>
    <span class="legend-item"><span class="class-conditional">Conditional</span> Conditionally required</span>
    <span class="legend-item"><span class="class-alias">Alias</span> Computed alias</span>
    <span class="legend-item"><span class="source-testeronly">Tester Only</span> In tester but not docs</span>
    <span class="legend-item"><span class="source-physicalonly">Physical Table Only</span> In table but not docs</span>
</div>
""")
        parts.append('</div>\n')  # Close fields sub-tab pane

        # ---- Parsers Sub-tab ----
        parts.append(f'<div class="tab-pane fade" id="{schema_id}-parsers-pane" role="tabpanel">\n')

        if schema_parsers:
            parts.append(f"""\
<table id="{schema_id}-parsers-table" class="table table-striped table-hover" style="width:100%">
<thead>
<tr>
    <th>Parser</th><th>Version</th><th>Product</th><th>Tables</th><th>Solutions</th>
</tr>
<tr class="filters">
    <th></th><th></th><th></th><th></th><th></th>
</tr>
</thead>
<tbody>
""")

            for p in schema_parsers:
                ptype = p.get('parser_type', '')
                if ptype == 'empty':
                    continue
                name = p.get('parser_name', '')
                if not name:
                    continue

                product = p.get('product_name', '')
                version = p.get('parser_version', '')
                tables = p.get('tables', '').replace(';', ', ')

                # Link to parser doc page
                parser_link = f'<a href="{docs_base_path}asim/{sanitize_filename(name)}{link_extension}">{esc(name)}</a>'

                # Solution links
                sol_parts = []
                solutions = p.get('associated_solutions', '')
                if solutions:
                    for sol in [s.strip() for s in solutions.split(',') if s.strip()]:
                        sol_parts.append(f'<a href="{docs_base_path}solutions/{sanitize_filename(sol)}{link_extension}">{esc(sol)}</a>')
                sols_html = ', '.join(sol_parts) if sol_parts else ''

                parts.append(
                    f'<tr><td>{parser_link}</td>'
                    f'<td>{esc(version)}</td><td>{esc(product)}</td>'
                    f'<td>{esc(tables)}</td><td>{sols_html}</td></tr>\n'
                )

            parts.append('</tbody></table>\n')
        else:
            parts.append('<p class="text-muted mt-3">No parsers available for this schema.</p>\n')

        parts.append('</div>\n')  # Close parsers sub-tab pane
        parts.append('</div>\n')  # Close sub-tab-content
        parts.append('</div>\n')  # Close schema pane

    parts.append('</div><!-- schemaTabContent -->\n')

    # ---- Footer ----
    parts.append("""\
<div class="footer">
    Generated by Microsoft Sentinel Solutions Analyzer &mdash; ASIM Schema Browser
</div>

</div><!-- container -->

<!-- Scripts -->
<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.datatables.net/1.13.8/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.13.8/js/dataTables.bootstrap5.min.js"></script>
<script>
""")
    parts.append(_generate_js())
    parts.append("""\
</script>
</body>
</html>
""")

    # Write output
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / "asim-browser.html"
    output_path.write_text("".join(parts), encoding='utf-8')
    print(f"  ASIM Browser generated: {output_path}")
    return output_path


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    """CLI entry point."""
    parser = argparse.ArgumentParser(
        description="Generate interactive ASIM Schema Browser HTML page."
    )
    script_dir = Path(__file__).parent

    parser.add_argument(
        '--fields-csv',
        type=Path,
        default=script_dir / 'asim_fields.csv',
        help='Path to asim_fields.csv (default: asim_fields.csv in script directory)',
    )
    parser.add_argument(
        '--parsers-csv',
        type=Path,
        default=script_dir / 'asim_parsers.csv',
        help='Path to asim_parsers.csv (default: asim_parsers.csv in script directory)',
    )
    parser.add_argument(
        '--output-dir',
        type=Path,
        default=script_dir,
        help='Output directory for asim-browser.html (default: script directory)',
    )
    parser.add_argument(
        '--docs-base-path',
        type=str,
        default='',
        help='Relative path prefix from asim-browser.html to entity doc pages '
             '(e.g. "Solutions Docs/" when the page is at repo root)',
    )
    parser.add_argument(
        '--index-url',
        type=str,
        default='',
        help='URL to the main index.html page for the navbar link',
    )
    parser.add_argument(
        '--link-extension',
        type=str,
        default='.html',
        help='File extension for entity page links (default: .html)',
    )

    args = parser.parse_args()

    # Normalize docs base path
    if args.docs_base_path and not args.docs_base_path.endswith('/'):
        args.docs_base_path += '/'

    generate_asim_browser(
        fields_csv=args.fields_csv,
        parsers_csv=args.parsers_csv,
        output_dir=args.output_dir,
        docs_base_path=args.docs_base_path,
        index_url=args.index_url,
        link_extension=args.link_extension,
    )


if __name__ == '__main__':
    main()
