id: fc36d683-385a-4ec2-842d-2982dbed97a4
name: Prohibited Applications Spawning cmd.exe or powershell.exe
description: |
  'Hunts for commonly utilized Microsoft programs (Word, Excel, Publisher, etc) and other programs known to malicious launch powershell or cmd, such as Internet Explorer, Chrome and Firefox.'
requiredDataConnectors:
  - connectorId: SecurityEvent
    dataTypes:
      - SecurityEvent
tactics:
  - CommandandControl
relevantTechniques:
  - T1102
query: |
  let StartDate = ago(1d);
  SecurityEvent
  | where TimeGenerated > StartDate
  | where NewProcessName has_any (
    "winword.exe",
    "EXCEL.EXE",
    "OUTLOOK.EXE",
    "POWERPNT.EXE",
    "visio.exe",
    "mspub.exe",
    "Acrobat.exe",
    "Acrord32.exe",
    "chrome.exe",
    "iexplore.exe",
    "opera.exe",
    "firefox.exe",
    "mshta.exe",
    "zoom.exe",
    "utilman.exe"
  )
  | where NewProcessName has_any (
    "cmd.exe",
    "powershell.exe"
  )
  | project TimeGenerated, Computer, tostring(EventID), ParentProcessName, NewProcessName, CommandLine, SubjectUserName, SourceComputerId, processID=tolong(NewProcessId), parentProcessID=tolong(ProcessId), EventData| order by TimeGenerated
version: 1.0.0