id: cf40c2f6-2d70-4ff4-9d7b-c6ae12282b0a
name: TI map IP entity to Duo Security
description: |
    'As part of content migration, this file is moved to new location. you can find here: https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Threat%20Intelligence/Analytic%20Rules/IPEntity_DuoSecurity.yaml'
version: 1.0.1
