jobs:
- job: "DetectionTemplateSchemaValidation"
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    buildConfiguration: 'Release'
    dotnetSdkVersion: '3.1.401'
    PRNUM: $(System.PullRequest.PullRequestNumber)
  steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK $(dotnetSdkVersion)'
      inputs:
        version: '$(dotnetSdkVersion)'
    - task: DotNetCoreCLI@2
      displayName: 'Run Detection template structure validation tests'
      inputs:
        command: 'test'
        arguments: '--configuration $(buildConfiguration)'
        publishTestResults: true
        projects: '**/DetectionTemplateSchemaValidation.Tests.csproj'