jobs:
- job: "JsonFileValidation"
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: 'npm install -g npm@6.14.15;which npm;npm -v'
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      verbose: false
  - script: 'npm run tsc && node .script/jsonFileValidator.js'
    displayName: 'Json File Syntax Validation'
