let GetClassificationList = (_startDate:datetime, _endDate: datetime, _subscriptions:dynamic = dynamic("*"), _resourceGroups:dynamic = dynamic(["*"]), _userAccounts:dynamic = dynamic(["*"])) 
{ 
    DSTIMCorrelatedLogs(_dateStart, _dateEnd, _subscriptions, _resourceGroups, _userAccounts)
| mv-expand Classifications = todynamic(Classification)
| where isnotempty( Classifications.['Name'])
| project Classification=tostring(Classifications.['Name'])
| distinct Classification
};