id: 06a2c253-1549-4fc3-8afa-d9c5e1888da7
name: Changes to AWS Security Group ingress and egress settings
description: |
 'As part of content migration, this file is moved to new location. you can find here: https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Amazon%20Web%20Services/Analytic%20Rules/AWS_IngressEgressSecurityGroupChange.yaml'
version: 1.0.1