name: Pull Request Comment

on:  
  workflow_call:
    inputs:
      message:
        required: true
        type: string
      prNumber:
        required: false
        type: string

env:
  GITHUB_APPS_ID: "${{ secrets.APPLICATION_ID }}"
  GITHUB_APPS_KEY: "${{ secrets.APPLICATION_PRIVATE_KEY }}"

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@46e4a501e119d39574a54e53a06c9a705efc55c9
        with:
          app-id: ${{ env.GITHUB_APPS_ID }}
          private-key: ${{ env.GITHUB_APPS_KEY }}

      - uses: actions/github-script@b7fb2001b410c9390cbe9e2c7d5cab7eefb7b29c
        env:
          MESSAGE: ${{ inputs.message}}
          PR_NUMBER: ${{ inputs.prNumber }}
          APPTOKEN: ${{ steps.generate_token.outputs.token }}
        with:
          github-token: ${{ env.APPTOKEN }}
          script: |
            $prNumber = process.env.PR_NUMBER
            $prNumber = $prNumber ? $prNumber : context.issue.number

            github.rest.issues.createComment({
              issue_number: $prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: process.env.MESSAGE
            })
