name: Allowed To Run Workflow

on:
  workflow_call:
    outputs:
      isWorkflowRunAllowed:
        description: "Is Allowed to run this workflow!"
        value: ${{ jobs.allowedWorkflowRunUsers.outputs.isWorkflowRunAllowed }}

env:
  ALLOWED_USERS: "${{ vars.ALLOWEDUSERS }}"

jobs:
  allowedWorkflowRunUsers:
    if: ${{ !github.event.pull_request.head.repo.fork }}
    name: Is Workflow Run Allowed To Current User
    runs-on: ubuntu-latest
    outputs:
      isWorkflowRunAllowed: ${{ steps.getWorkflowRunAllowedStatus.outputs.isWorkflowRunAllowed }}
    steps:
      - name: Is Current User Allowed
        shell: pwsh
        id: getWorkflowRunAllowedStatus
        run: |          
          $allowedUsers = "${{ env.ALLOWED_USERS }}"
          $currentUser = "${{ github.actor }}"
          $isAllowedUser = $allowedUsers.Contains($currentUser)
          Write-Host "currentUser $currentUser , isAllowedUser $isAllowedUser"
          if ($isAllowedUser)
          {
            Write-Host "User is allowed to perform execution of workflow!"
          }
          else
          {
            Write-Host "User is Not allowed to perform execution of workflow!"
          }
          Write-Output "isWorkflowRunAllowed=$isAllowedUser" >> $env:GITHUB_OUTPUT
