name: Detection Template Schema Validations
run-name: Detection Template Schema Validations running on ${{ github.ref_name }} 
on:
    pull_request:
        branches:
            - master
    # Allows to run workflow manually from the Actions tab
    workflow_dispatch:
jobs:
    DetectionTemplateSchemaValidation:
      runs-on: ubuntu-latest
      env:
        buildConfiguration: Release
        dotnetSdkVersion: 3.1.401
        PRNUM: ${{ github.event.pull_request.number }}
      steps:
      - uses: actions/checkout@v4
      - name: Use .NET Core SDK ${{ env.dotnetSdkVersion }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.dotnetSdkVersion }}
      - name: Run Detection template structure validation tests
        run: dotnet test .script/tests/detectionTemplateSchemaValidation/DetectionTemplateSchemaValidation.Tests.csproj --configuration ${{ env.buildConfiguration }}
                      