name: JSON File Syntax Validation
run-name: JSON File Syntax Validation running on ${{ github.ref_name }} 
on:
    pull_request:
        branches:
            - master
    # Allows to run workflow manually from the Actions tab
    workflow_dispatch:
jobs:
    JsonFileValidation:
      runs-on: ubuntu-latest
      env:
        REPO_OWNER: ${{ github.event.pull_request.base.repo.owner.login }}
        REPO_NAME: ${{ github.event.pull_request.base.repo.name }}
        PRNUM: ${{ github.event.pull_request.number }}
        GITHUBAPPID: ${{ secrets.APPLICATION_ID }}
        GITHUBAPPINSTALLATIONID: ${{ secrets.APPLICATION_INSTALLATION_ID }}
        GITHUBAPPPRIVATEKEY: ${{ secrets.APPLICATION_PRIVATE_KEY }}
        SYSTEM_PULLREQUEST_ISFORK: ${{ github.event.pull_request.head.repo.fork }}
      steps:
      - uses: actions/checkout@v4
      - run: npm install -g npm@6.14.18;which npm;npm -v
      - name: npm install
        run: npm install
      - name: Json File Syntax Validation
        run: npm run tsc && node .script/jsonFileValidator.js