name: Non-Ascii Validations
run-name: Non-Ascii validation running on ${{ github.ref_name }} 
on:
    pull_request:
        branches:
            - master

    # Allows to run workflow manually from the Actions tab
    workflow_dispatch:
jobs:
    NonAsciiValidations:
      runs-on: ubuntu-22.04
      env:
        buildConfiguration: Release
        dotnetSdkVersion: 3.1.401
      steps:
      - uses: actions/checkout@v4
      - name: Use .NET Core SDK ${{ env.dotnetSdkVersion }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.dotnetSdkVersion }}
      - name: Run Non-Ascii validation tests
        run: dotnet test .script/tests/NonAsciiValidationsTests/NonAsciiValidations.Tests.csproj --configuration ${{ env.buildConfiguration }}
                      