name: Non-Ascii Validations
run-name: Non-Ascii validation running on ${{ github.ref }} 
on:
    pull_request:
        branches:
            - master

    # Allows to run workflow manually from the Actions tab
    workflow_dispatch:
jobs:
    NonAsciiValidations:
      runs-on: ubuntu-latest
      env:
        buildConfiguration: Release
        dotnetSdkVersion: 3.1.401
      steps:
      - uses: actions/checkout@v2
      - name: Use .NET Core SDK ${{ env.dotnetSdkVersion }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.dotnetSdkVersion }}
      - name: Run kql validation tests
        run: dotnet test **/NonAsciiValidations.Tests.csproj --configuration ${{ env.buildConfiguration }}
                      