name: Pull Request Status

on:
  workflow_call:
    outputs:
      isPullRequestMerged:
        description: "Is pull request merged in master branch."
        value: ${{ jobs.pullRequestStatus.outputs.isPullRequestMerged }}

jobs:
  pullRequestStatus:
    name: Pull Request Status
    runs-on: ubuntu-latest
    outputs:
        isPullRequestMerged: ${{ steps.getPullRequestStatus.outputs.isPullRequestMerged }}
    steps:
      - name: Get Pull Request Status
        shell: pwsh
        id: getPullRequestStatus
        run: |
          $prStatus = "${{ github.event.issue.state }}"
          $prMerged = "${{ github.event.issue.pull_request.merged_at }}"
          $isPullRequestMerged = $false
          Write-Host "prStatus $prStatus, prMerged $prMerged"
          if ($prMerged -ne '' -and $null -ne $prMerged -and $prStatus -eq 'closed')
          {
            # PR is merged in master
            $isPullRequestMerged = $true
          }

          Write-Output "isPullRequestMerged=$isPullRequestMerged" >> $env:GITHUB_OUTPUT
          Write-Host "Pull Request Status is $isPullRequestMerged"
