name: Scanning for secrets in commits
on:
  pull_request:
    branches:
      - master
permissions:
  contents: read
  pull-requests: write
jobs:
  Scan_Secrets_in_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 10
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@27b0417c16317ca9a472a9a8092acce143b49c55 # v3.95.9
        with:
          extra_args: --exclude-paths=.script/SecretScanning/Excludepathlist --only-verified
