name: Deploy Content to sentinel-secopdev [c8e9b9b6-d679-49f6-b431-19b6f9d61d1b]
# Note: This workflow will deploy everything in the root directory.
# To deploy content only from a specific path (for example SentinelContent):
#   1. Add the target path to the "paths" property like such
#    paths:
#    - 'SentinelContent/**'
#    - '!.github/workflows/**'
#    - '.github/workflows/sentinel-deploy-c8e9b9b6-d679-49f6-b431-19b6f9d61d1b.yml'
#   2. Append the path to the directory environment variable below
#       directory: '${{ github.workspace }}/SentinelContent'

on:
  push:
    branches: [ master ]
    paths:
    - '**'
    - '!.github/workflows/**'  # this filter prevents other workflow changes from triggering this workflow
    - '.github/workflows/sentinel-deploy-c8e9b9b6-d679-49f6-b431-19b6f9d61d1b.yml'

jobs:
  deploy-content:
    runs-on: windows-latest
    env:
      resourceGroupName: 'secopdev'
      workspaceName: 'sentinel-secopdev'
      workspaceId: '18602308-599e-4206-8319-6604f1e1238e'
      directory: '${{ github.workspace }}'
      cloudEnv: 'AzureCloud'
      contentTypes: 'AnalyticsRule,AutomationRule,HuntingQuery,Parser,Playbook,Workbook,Watchlist'
      branch: 'master'
      sourceControlId: 'c8e9b9b6-d679-49f6-b431-19b6f9d61d1b'
      rootDirectory: '${{ github.workspace }}'
      githubAuthToken: ${{ secrets.GITHUB_TOKEN }}
      smartDeployment: 'true'
    permissions:
      contents: write
      id-token: write # Require write permission to Fetch an OIDC token.

    steps:
    - name: Login to Azure (Attempt 1)
      continue-on-error: true
      id: login1
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_c8e9b9b6d67949f6b43119b6f9d61d1b }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_c8e9b9b6d67949f6b43119b6f9d61d1b }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_c8e9b9b6d67949f6b43119b6f9d61d1b }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 1 failed
      if: ${{ steps.login1.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 2)
      continue-on-error: true
      id: login2
      uses: azure/login@v2
      if: ${{ steps.login1.outcome=='failure' }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_c8e9b9b6d67949f6b43119b6f9d61d1b }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_c8e9b9b6d67949f6b43119b6f9d61d1b }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_c8e9b9b6d67949f6b43119b6f9d61d1b }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 2 failed
      if: ${{ steps.login2.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 3)
      continue-on-error: false
      id: login3
      uses: azure/login@v2
      if: ${{ steps.login2.outcome=='failure'  }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_c8e9b9b6d67949f6b43119b6f9d61d1b }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_c8e9b9b6d67949f6b43119b6f9d61d1b }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_c8e9b9b6d67949f6b43119b6f9d61d1b }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy Content to Microsoft Sentinel
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          ${{ github.workspace }}//.github/workflows/azure-sentinel-deploy-c8e9b9b6-d679-49f6-b431-19b6f9d61d1b.ps1