name: Workbook Metadata Validations
run-name: Workbook Metadata Validations running on ${{ github.ref_name }} 
on:
    pull_request:
        branches:
            - master
    # Allows to run workflow manually from the Actions tab
    workflow_dispatch:
jobs:
    WorkbooksValidations:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - run: npm install -g npm@6.14.15;which npm;npm -v
      - name: npm install
        run: npm install
      - name: Workbooks Metadata Validations
        run: npm run tsc && node .script/workbooksMetadataValidator.js